package br.gov.pa.prodepa;
// Generated Nov 1, 2019 4:29:22 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AgendaAtendimentoUsuariaId generated by hbm2java
 */
@Embeddable
public class AgendaAtendimentoUsuariaId implements java.io.Serializable {

	private long idAgendaAtendimento;
	private long idUsuaria;

	public AgendaAtendimentoUsuariaId() {
	}

	public AgendaAtendimentoUsuariaId(long idAgendaAtendimento, long idUsuaria) {
		this.idAgendaAtendimento = idAgendaAtendimento;
		this.idUsuaria = idUsuaria;
	}

	@Column(name = "id_agenda_atendimento", nullable = false)
	public long getIdAgendaAtendimento() {
		return this.idAgendaAtendimento;
	}

	public void setIdAgendaAtendimento(long idAgendaAtendimento) {
		this.idAgendaAtendimento = idAgendaAtendimento;
	}

	@Column(name = "id_usuaria", nullable = false)
	public long getIdUsuaria() {
		return this.idUsuaria;
	}

	public void setIdUsuaria(long idUsuaria) {
		this.idUsuaria = idUsuaria;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AgendaAtendimentoUsuariaId))
			return false;
		AgendaAtendimentoUsuariaId castOther = (AgendaAtendimentoUsuariaId) other;

		return (this.getIdAgendaAtendimento() == castOther.getIdAgendaAtendimento())
				&& (this.getIdUsuaria() == castOther.getIdUsuaria());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdAgendaAtendimento();
		result = 37 * result + (int) this.getIdUsuaria();
		return result;
	}

}
