package br.gov.pa.prodepa;
// Generated Nov 1, 2019 4:29:22 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AgendaTecnico generated by hbm2java
 */
@Entity
@Table(name = "agenda_tecnico")
public class AgendaTecnico implements java.io.Serializable {

	private long id;
	private AgendaAtendimento agendaAtendimento;
	private Centro centro;
	private Tecnico tecnico;
	private Date dataAgendada;
	private int horaAgendamento;
	private int tipoAtividade;
	private String observacao;
	private int statusAgeTecnico;
	private int diaSemana;
	private Long idTecnicoCriacao;
	private Long idTecnicoAlteracao;
	private Date dataCriacao;
	private Date dataAlteracao;

	public AgendaTecnico() {
	}

	public AgendaTecnico(long id, Centro centro, Tecnico tecnico, Date dataAgendada, int horaAgendamento,
			int tipoAtividade, int statusAgeTecnico, int diaSemana) {
		this.id = id;
		this.centro = centro;
		this.tecnico = tecnico;
		this.dataAgendada = dataAgendada;
		this.horaAgendamento = horaAgendamento;
		this.tipoAtividade = tipoAtividade;
		this.statusAgeTecnico = statusAgeTecnico;
		this.diaSemana = diaSemana;
	}

	public AgendaTecnico(long id, AgendaAtendimento agendaAtendimento, Centro centro, Tecnico tecnico,
			Date dataAgendada, int horaAgendamento, int tipoAtividade, String observacao, int statusAgeTecnico,
			int diaSemana, Long idTecnicoCriacao, Long idTecnicoAlteracao, Date dataCriacao, Date dataAlteracao) {
		this.id = id;
		this.agendaAtendimento = agendaAtendimento;
		this.centro = centro;
		this.tecnico = tecnico;
		this.dataAgendada = dataAgendada;
		this.horaAgendamento = horaAgendamento;
		this.tipoAtividade = tipoAtividade;
		this.observacao = observacao;
		this.statusAgeTecnico = statusAgeTecnico;
		this.diaSemana = diaSemana;
		this.idTecnicoCriacao = idTecnicoCriacao;
		this.idTecnicoAlteracao = idTecnicoAlteracao;
		this.dataCriacao = dataCriacao;
		this.dataAlteracao = dataAlteracao;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_agenda_atendimento")
	public AgendaAtendimento getAgendaAtendimento() {
		return this.agendaAtendimento;
	}

	public void setAgendaAtendimento(AgendaAtendimento agendaAtendimento) {
		this.agendaAtendimento = agendaAtendimento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_centro", nullable = false)
	public Centro getCentro() {
		return this.centro;
	}

	public void setCentro(Centro centro) {
		this.centro = centro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tecnico", nullable = false)
	public Tecnico getTecnico() {
		return this.tecnico;
	}

	public void setTecnico(Tecnico tecnico) {
		this.tecnico = tecnico;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data_agendada", nullable = false, length = 13)
	public Date getDataAgendada() {
		return this.dataAgendada;
	}

	public void setDataAgendada(Date dataAgendada) {
		this.dataAgendada = dataAgendada;
	}

	@Column(name = "hora_agendamento", nullable = false)
	public int getHoraAgendamento() {
		return this.horaAgendamento;
	}

	public void setHoraAgendamento(int horaAgendamento) {
		this.horaAgendamento = horaAgendamento;
	}

	@Column(name = "tipo_atividade", nullable = false)
	public int getTipoAtividade() {
		return this.tipoAtividade;
	}

	public void setTipoAtividade(int tipoAtividade) {
		this.tipoAtividade = tipoAtividade;
	}

	@Column(name = "observacao")
	public String getObservacao() {
		return this.observacao;
	}

	public void setObservacao(String observacao) {
		this.observacao = observacao;
	}

	@Column(name = "status_age_tecnico", nullable = false)
	public int getStatusAgeTecnico() {
		return this.statusAgeTecnico;
	}

	public void setStatusAgeTecnico(int statusAgeTecnico) {
		this.statusAgeTecnico = statusAgeTecnico;
	}

	@Column(name = "dia_semana", nullable = false)
	public int getDiaSemana() {
		return this.diaSemana;
	}

	public void setDiaSemana(int diaSemana) {
		this.diaSemana = diaSemana;
	}

	@Column(name = "id_tecnico_criacao")
	public Long getIdTecnicoCriacao() {
		return this.idTecnicoCriacao;
	}

	public void setIdTecnicoCriacao(Long idTecnicoCriacao) {
		this.idTecnicoCriacao = idTecnicoCriacao;
	}

	@Column(name = "id_tecnico_alteracao")
	public Long getIdTecnicoAlteracao() {
		return this.idTecnicoAlteracao;
	}

	public void setIdTecnicoAlteracao(Long idTecnicoAlteracao) {
		this.idTecnicoAlteracao = idTecnicoAlteracao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_criacao", length = 29)
	public Date getDataCriacao() {
		return this.dataCriacao;
	}

	public void setDataCriacao(Date dataCriacao) {
		this.dataCriacao = dataCriacao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_alteracao", length = 29)
	public Date getDataAlteracao() {
		return this.dataAlteracao;
	}

	public void setDataAlteracao(Date dataAlteracao) {
		this.dataAlteracao = dataAlteracao;
	}

}
