package br.gov.pa.prodepa;
// Generated Nov 1, 2019 4:29:22 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AgressorTipoMedicacao generated by hbm2java
 */
@Entity
@Table(name = "agressor_tipo_medicacao")
public class AgressorTipoMedicacao implements java.io.Serializable {

	private AgressorTipoMedicacaoId id;
	private Agressor agressor;
	private TipoMedicacao tipoMedicacao;
	private int frequenciaUso;

	public AgressorTipoMedicacao() {
	}

	public AgressorTipoMedicacao(AgressorTipoMedicacaoId id, Agressor agressor, TipoMedicacao tipoMedicacao,
			int frequenciaUso) {
		this.id = id;
		this.agressor = agressor;
		this.tipoMedicacao = tipoMedicacao;
		this.frequenciaUso = frequenciaUso;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idAgressor", column = @Column(name = "id_agressor", nullable = false)),
			@AttributeOverride(name = "idTipoMedicacao", column = @Column(name = "id_tipo_medicacao", nullable = false)) })
	public AgressorTipoMedicacaoId getId() {
		return this.id;
	}

	public void setId(AgressorTipoMedicacaoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_agressor", nullable = false, insertable = false, updatable = false)
	public Agressor getAgressor() {
		return this.agressor;
	}

	public void setAgressor(Agressor agressor) {
		this.agressor = agressor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_medicacao", nullable = false, insertable = false, updatable = false)
	public TipoMedicacao getTipoMedicacao() {
		return this.tipoMedicacao;
	}

	public void setTipoMedicacao(TipoMedicacao tipoMedicacao) {
		this.tipoMedicacao = tipoMedicacao;
	}

	@Column(name = "frequencia_uso", nullable = false)
	public int getFrequenciaUso() {
		return this.frequenciaUso;
	}

	public void setFrequenciaUso(int frequenciaUso) {
		this.frequenciaUso = frequenciaUso;
	}

}
