package br.gov.pa.prodepa;
// Generated Nov 1, 2019 4:29:22 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AgressorTipoEntorpecente generated by hbm2java
 */
@Entity
@Table(name = "agressor_tipo_entorpecente")
public class AgressorTipoEntorpecente implements java.io.Serializable {

	private AgressorTipoEntorpecenteId id;
	private Agressor agressor;
	private TipoEntorpecente tipoEntorpecente;
	private Integer frequenciaUso;
	private Integer fazUso;

	public AgressorTipoEntorpecente() {
	}

	public AgressorTipoEntorpecente(AgressorTipoEntorpecenteId id, Agressor agressor,
			TipoEntorpecente tipoEntorpecente) {
		this.id = id;
		this.agressor = agressor;
		this.tipoEntorpecente = tipoEntorpecente;
	}

	public AgressorTipoEntorpecente(AgressorTipoEntorpecenteId id, Agressor agressor, TipoEntorpecente tipoEntorpecente,
			Integer frequenciaUso, Integer fazUso) {
		this.id = id;
		this.agressor = agressor;
		this.tipoEntorpecente = tipoEntorpecente;
		this.frequenciaUso = frequenciaUso;
		this.fazUso = fazUso;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idAgressor", column = @Column(name = "id_agressor", nullable = false)),
			@AttributeOverride(name = "idTipoEntorpecente", column = @Column(name = "id_tipo_entorpecente", nullable = false)) })
	public AgressorTipoEntorpecenteId getId() {
		return this.id;
	}

	public void setId(AgressorTipoEntorpecenteId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_agressor", nullable = false, insertable = false, updatable = false)
	public Agressor getAgressor() {
		return this.agressor;
	}

	public void setAgressor(Agressor agressor) {
		this.agressor = agressor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_entorpecente", nullable = false, insertable = false, updatable = false)
	public TipoEntorpecente getTipoEntorpecente() {
		return this.tipoEntorpecente;
	}

	public void setTipoEntorpecente(TipoEntorpecente tipoEntorpecente) {
		this.tipoEntorpecente = tipoEntorpecente;
	}

	@Column(name = "frequencia_uso")
	public Integer getFrequenciaUso() {
		return this.frequenciaUso;
	}

	public void setFrequenciaUso(Integer frequenciaUso) {
		this.frequenciaUso = frequenciaUso;
	}

	@Column(name = "faz_uso")
	public Integer getFazUso() {
		return this.fazUso;
	}

	public void setFazUso(Integer fazUso) {
		this.fazUso = fazUso;
	}

}
