package br.gov.pa.prodepa;
// Generated Nov 1, 2019 4:29:22 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AgressorTipoEntorpecenteId generated by hbm2java
 */
@Embeddable
public class AgressorTipoEntorpecenteId implements java.io.Serializable {

	private long idAgressor;
	private long idTipoEntorpecente;

	public AgressorTipoEntorpecenteId() {
	}

	public AgressorTipoEntorpecenteId(long idAgressor, long idTipoEntorpecente) {
		this.idAgressor = idAgressor;
		this.idTipoEntorpecente = idTipoEntorpecente;
	}

	@Column(name = "id_agressor", nullable = false)
	public long getIdAgressor() {
		return this.idAgressor;
	}

	public void setIdAgressor(long idAgressor) {
		this.idAgressor = idAgressor;
	}

	@Column(name = "id_tipo_entorpecente", nullable = false)
	public long getIdTipoEntorpecente() {
		return this.idTipoEntorpecente;
	}

	public void setIdTipoEntorpecente(long idTipoEntorpecente) {
		this.idTipoEntorpecente = idTipoEntorpecente;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AgressorTipoEntorpecenteId))
			return false;
		AgressorTipoEntorpecenteId castOther = (AgressorTipoEntorpecenteId) other;

		return (this.getIdAgressor() == castOther.getIdAgressor())
				&& (this.getIdTipoEntorpecente() == castOther.getIdTipoEntorpecente());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdAgressor();
		result = 37 * result + (int) this.getIdTipoEntorpecente();
		return result;
	}

}
