package br.gov.pa.prodepa;
// Generated Nov 1, 2019 4:29:22 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AgressorTipoMedicacaoId generated by hbm2java
 */
@Embeddable
public class AgressorTipoMedicacaoId implements java.io.Serializable {

	private long idAgressor;
	private long idTipoMedicacao;

	public AgressorTipoMedicacaoId() {
	}

	public AgressorTipoMedicacaoId(long idAgressor, long idTipoMedicacao) {
		this.idAgressor = idAgressor;
		this.idTipoMedicacao = idTipoMedicacao;
	}

	@Column(name = "id_agressor", nullable = false)
	public long getIdAgressor() {
		return this.idAgressor;
	}

	public void setIdAgressor(long idAgressor) {
		this.idAgressor = idAgressor;
	}

	@Column(name = "id_tipo_medicacao", nullable = false)
	public long getIdTipoMedicacao() {
		return this.idTipoMedicacao;
	}

	public void setIdTipoMedicacao(long idTipoMedicacao) {
		this.idTipoMedicacao = idTipoMedicacao;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AgressorTipoMedicacaoId))
			return false;
		AgressorTipoMedicacaoId castOther = (AgressorTipoMedicacaoId) other;

		return (this.getIdAgressor() == castOther.getIdAgressor())
				&& (this.getIdTipoMedicacao() == castOther.getIdTipoMedicacao());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdAgressor();
		result = 37 * result + (int) this.getIdTipoMedicacao();
		return result;
	}

}
