package br.gov.pa.prodepa;
// Generated Nov 1, 2019 4:29:22 PM by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Agressor generated by hbm2java
 */
@Entity
@Table(name = "agressor")
public class Agressor implements java.io.Serializable {

	private long id;
	private Ocupacao ocupacaoByIdOcupacaoProfissao;
	private Ocupacao ocupacaoByIdOcupacao;
	private Religiao religiao;
	private String nome;
	private Date dataNascimento;
	private BigDecimal valorRenda;
	private Integer possuiAntecedente;
	private Integer violentoComFamilia;
	private String descricaoViolentoComFamilia;
	private int fazUsoDroga;
	private int fazUsoMedicacao;
	private Integer fazUsoAlcool;
	private Date dataCadastro;
	private Integer frequenciaUsoAlcool;
	private Integer nivelEscolaridade;
	private int situacao;
	private Long usuario;
	private String observacao;
	private Integer idade;
	private Integer sexo;
	private Integer estadoCivil;
	private Integer raca;
	private Integer orientacaoSexual;
	private Integer realizouAgressaoOutras;
	private Integer quantasAgressoes;
	private Long idRendaFamiliar;
	private Set antecedenteCriminals = new HashSet(0);
	private Set detalheViolencias = new HashSet(0);
	private Set enderecos = new HashSet(0);
	private Set agressorTipoMedicacaos = new HashSet(0);
	private Set atendimentoAgressors = new HashSet(0);
	private Set agressorTipoEntorpecentes = new HashSet(0);

	public Agressor() {
	}

	public Agressor(long id, String nome, int fazUsoDroga, int fazUsoMedicacao, Date dataCadastro, int situacao) {
		this.id = id;
		this.nome = nome;
		this.fazUsoDroga = fazUsoDroga;
		this.fazUsoMedicacao = fazUsoMedicacao;
		this.dataCadastro = dataCadastro;
		this.situacao = situacao;
	}

	public Agressor(long id, Ocupacao ocupacaoByIdOcupacaoProfissao, Ocupacao ocupacaoByIdOcupacao, Religiao religiao,
			String nome, Date dataNascimento, BigDecimal valorRenda, Integer possuiAntecedente,
			Integer violentoComFamilia, String descricaoViolentoComFamilia, int fazUsoDroga, int fazUsoMedicacao,
			Integer fazUsoAlcool, Date dataCadastro, Integer frequenciaUsoAlcool, Integer nivelEscolaridade,
			int situacao, Long usuario, String observacao, Integer idade, Integer sexo, Integer estadoCivil,
			Integer raca, Integer orientacaoSexual, Integer realizouAgressaoOutras, Integer quantasAgressoes,
			Long idRendaFamiliar, Set antecedenteCriminals, Set detalheViolencias, Set enderecos,
			Set agressorTipoMedicacaos, Set atendimentoAgressors, Set agressorTipoEntorpecentes) {
		this.id = id;
		this.ocupacaoByIdOcupacaoProfissao = ocupacaoByIdOcupacaoProfissao;
		this.ocupacaoByIdOcupacao = ocupacaoByIdOcupacao;
		this.religiao = religiao;
		this.nome = nome;
		this.dataNascimento = dataNascimento;
		this.valorRenda = valorRenda;
		this.possuiAntecedente = possuiAntecedente;
		this.violentoComFamilia = violentoComFamilia;
		this.descricaoViolentoComFamilia = descricaoViolentoComFamilia;
		this.fazUsoDroga = fazUsoDroga;
		this.fazUsoMedicacao = fazUsoMedicacao;
		this.fazUsoAlcool = fazUsoAlcool;
		this.dataCadastro = dataCadastro;
		this.frequenciaUsoAlcool = frequenciaUsoAlcool;
		this.nivelEscolaridade = nivelEscolaridade;
		this.situacao = situacao;
		this.usuario = usuario;
		this.observacao = observacao;
		this.idade = idade;
		this.sexo = sexo;
		this.estadoCivil = estadoCivil;
		this.raca = raca;
		this.orientacaoSexual = orientacaoSexual;
		this.realizouAgressaoOutras = realizouAgressaoOutras;
		this.quantasAgressoes = quantasAgressoes;
		this.idRendaFamiliar = idRendaFamiliar;
		this.antecedenteCriminals = antecedenteCriminals;
		this.detalheViolencias = detalheViolencias;
		this.enderecos = enderecos;
		this.agressorTipoMedicacaos = agressorTipoMedicacaos;
		this.atendimentoAgressors = atendimentoAgressors;
		this.agressorTipoEntorpecentes = agressorTipoEntorpecentes;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_ocupacao_profissao")
	public Ocupacao getOcupacaoByIdOcupacaoProfissao() {
		return this.ocupacaoByIdOcupacaoProfissao;
	}

	public void setOcupacaoByIdOcupacaoProfissao(Ocupacao ocupacaoByIdOcupacaoProfissao) {
		this.ocupacaoByIdOcupacaoProfissao = ocupacaoByIdOcupacaoProfissao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_ocupacao")
	public Ocupacao getOcupacaoByIdOcupacao() {
		return this.ocupacaoByIdOcupacao;
	}

	public void setOcupacaoByIdOcupacao(Ocupacao ocupacaoByIdOcupacao) {
		this.ocupacaoByIdOcupacao = ocupacaoByIdOcupacao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_religiao")
	public Religiao getReligiao() {
		return this.religiao;
	}

	public void setReligiao(Religiao religiao) {
		this.religiao = religiao;
	}

	@Column(name = "nome", nullable = false)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data_nascimento", length = 13)
	public Date getDataNascimento() {
		return this.dataNascimento;
	}

	public void setDataNascimento(Date dataNascimento) {
		this.dataNascimento = dataNascimento;
	}

	@Column(name = "valor_renda", precision = 9)
	public BigDecimal getValorRenda() {
		return this.valorRenda;
	}

	public void setValorRenda(BigDecimal valorRenda) {
		this.valorRenda = valorRenda;
	}

	@Column(name = "possui_antecedente")
	public Integer getPossuiAntecedente() {
		return this.possuiAntecedente;
	}

	public void setPossuiAntecedente(Integer possuiAntecedente) {
		this.possuiAntecedente = possuiAntecedente;
	}

	@Column(name = "violento_com_familia")
	public Integer getViolentoComFamilia() {
		return this.violentoComFamilia;
	}

	public void setViolentoComFamilia(Integer violentoComFamilia) {
		this.violentoComFamilia = violentoComFamilia;
	}

	@Column(name = "descricao_violento_com_familia")
	public String getDescricaoViolentoComFamilia() {
		return this.descricaoViolentoComFamilia;
	}

	public void setDescricaoViolentoComFamilia(String descricaoViolentoComFamilia) {
		this.descricaoViolentoComFamilia = descricaoViolentoComFamilia;
	}

	@Column(name = "faz_uso_droga", nullable = false)
	public int getFazUsoDroga() {
		return this.fazUsoDroga;
	}

	public void setFazUsoDroga(int fazUsoDroga) {
		this.fazUsoDroga = fazUsoDroga;
	}

	@Column(name = "faz_uso_medicacao", nullable = false)
	public int getFazUsoMedicacao() {
		return this.fazUsoMedicacao;
	}

	public void setFazUsoMedicacao(int fazUsoMedicacao) {
		this.fazUsoMedicacao = fazUsoMedicacao;
	}

	@Column(name = "faz_uso_alcool")
	public Integer getFazUsoAlcool() {
		return this.fazUsoAlcool;
	}

	public void setFazUsoAlcool(Integer fazUsoAlcool) {
		this.fazUsoAlcool = fazUsoAlcool;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_cadastro", nullable = false, length = 29)
	public Date getDataCadastro() {
		return this.dataCadastro;
	}

	public void setDataCadastro(Date dataCadastro) {
		this.dataCadastro = dataCadastro;
	}

	@Column(name = "frequencia_uso_alcool")
	public Integer getFrequenciaUsoAlcool() {
		return this.frequenciaUsoAlcool;
	}

	public void setFrequenciaUsoAlcool(Integer frequenciaUsoAlcool) {
		this.frequenciaUsoAlcool = frequenciaUsoAlcool;
	}

	@Column(name = "nivel_escolaridade")
	public Integer getNivelEscolaridade() {
		return this.nivelEscolaridade;
	}

	public void setNivelEscolaridade(Integer nivelEscolaridade) {
		this.nivelEscolaridade = nivelEscolaridade;
	}

	@Column(name = "situacao", nullable = false)
	public int getSituacao() {
		return this.situacao;
	}

	public void setSituacao(int situacao) {
		this.situacao = situacao;
	}

	@Column(name = "usuario")
	public Long getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Long usuario) {
		this.usuario = usuario;
	}

	@Column(name = "observacao")
	public String getObservacao() {
		return this.observacao;
	}

	public void setObservacao(String observacao) {
		this.observacao = observacao;
	}

	@Column(name = "idade")
	public Integer getIdade() {
		return this.idade;
	}

	public void setIdade(Integer idade) {
		this.idade = idade;
	}

	@Column(name = "sexo")
	public Integer getSexo() {
		return this.sexo;
	}

	public void setSexo(Integer sexo) {
		this.sexo = sexo;
	}

	@Column(name = "estado_civil")
	public Integer getEstadoCivil() {
		return this.estadoCivil;
	}

	public void setEstadoCivil(Integer estadoCivil) {
		this.estadoCivil = estadoCivil;
	}

	@Column(name = "raca")
	public Integer getRaca() {
		return this.raca;
	}

	public void setRaca(Integer raca) {
		this.raca = raca;
	}

	@Column(name = "orientacao_sexual")
	public Integer getOrientacaoSexual() {
		return this.orientacaoSexual;
	}

	public void setOrientacaoSexual(Integer orientacaoSexual) {
		this.orientacaoSexual = orientacaoSexual;
	}

	@Column(name = "realizou_agressao_outras")
	public Integer getRealizouAgressaoOutras() {
		return this.realizouAgressaoOutras;
	}

	public void setRealizouAgressaoOutras(Integer realizouAgressaoOutras) {
		this.realizouAgressaoOutras = realizouAgressaoOutras;
	}

	@Column(name = "quantas_agressoes")
	public Integer getQuantasAgressoes() {
		return this.quantasAgressoes;
	}

	public void setQuantasAgressoes(Integer quantasAgressoes) {
		this.quantasAgressoes = quantasAgressoes;
	}

	@Column(name = "id_renda_familiar")
	public Long getIdRendaFamiliar() {
		return this.idRendaFamiliar;
	}

	public void setIdRendaFamiliar(Long idRendaFamiliar) {
		this.idRendaFamiliar = idRendaFamiliar;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "agressor_antecedente_criminal", joinColumns = {
			@JoinColumn(name = "id_agressor", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "id_antecedente_criminal", nullable = false, updatable = false) })
	public Set getAntecedenteCriminals() {
		return this.antecedenteCriminals;
	}

	public void setAntecedenteCriminals(Set antecedenteCriminals) {
		this.antecedenteCriminals = antecedenteCriminals;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "agressor_detalhe_violencia", joinColumns = {
			@JoinColumn(name = "id_agressor", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "id_detalhe_violencia", nullable = false, updatable = false) })
	public Set getDetalheViolencias() {
		return this.detalheViolencias;
	}

	public void setDetalheViolencias(Set detalheViolencias) {
		this.detalheViolencias = detalheViolencias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "agressor")
	public Set getEnderecos() {
		return this.enderecos;
	}

	public void setEnderecos(Set enderecos) {
		this.enderecos = enderecos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "agressor")
	public Set getAgressorTipoMedicacaos() {
		return this.agressorTipoMedicacaos;
	}

	public void setAgressorTipoMedicacaos(Set agressorTipoMedicacaos) {
		this.agressorTipoMedicacaos = agressorTipoMedicacaos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "agressor")
	public Set getAtendimentoAgressors() {
		return this.atendimentoAgressors;
	}

	public void setAtendimentoAgressors(Set atendimentoAgressors) {
		this.atendimentoAgressors = atendimentoAgressors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "agressor")
	public Set getAgressorTipoEntorpecentes() {
		return this.agressorTipoEntorpecentes;
	}

	public void setAgressorTipoEntorpecentes(Set agressorTipoEntorpecentes) {
		this.agressorTipoEntorpecentes = agressorTipoEntorpecentes;
	}

}
