package br.gov.pa.prodepa;
// Generated Nov 1, 2019 4:29:22 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Atendimento generated by hbm2java
 */
@Entity
@Table(name = "atendimento", uniqueConstraints = @UniqueConstraint(columnNames = "numero_bo"))
public class Atendimento implements java.io.Serializable {

	private long id;
	private AgendaAtendimento agendaAtendimento;
	private Centro centro;
	private ClassificacaoCaso classificacaoCaso;
	private Endereco endereco;
	private LocalInternacao localInternacao;
	private LocalOcorrencia localOcorrencia;
	private PreAcolhimento preAcolhimento;
	private SituacaoCaso situacaoCaso;
	private Tecnico tecnico;
	private UnidadeTempo unidadeTempo;
	private Usuaria usuaria;
	private Date dataCadastro;
	private Date dataOcorrencia;
	private Integer tempoUltimaViolencia;
	private Integer recorreuServicoAtendimento;
	private Integer realizouDenuncia;
	private String resultadoDenuncia;
	private String dificuldadeEncontradaDenuncia;
	private String descricaoCaso;
	private String providenciaTomada;
	private Integer planoSeguranca;
	private String medidasPlanoSeguranca;
	private String motivoDesligamento;
	private Date dataDesligamento;
	private int status;
	private long usuario;
	private Integer situacaoUsuaria;
	private Integer sofreAmeacaMorte;
	private Integer valTempoViolencia;
	private Double valTempoViolenciaUb;
	private Integer riscoIntegridadeFisica;
	private Integer periodoOcorrencia;
	private Long idTecnicoCriacao;
	private Long idTecnicoAlteracao;
	private Date dataCriacao;
	private Date dataAlteracao;
	private String horaOcorrencia;
	private Integer vitimaFicouInternada;
	private Integer valTempoInternacao;
	private String localInternacao_1;
	private String agravantes;
	private Integer tipoEvento;
	private String numeroBo;
	private Date dataFormulario;
	private String evolucao;
	private Integer frida;
	private Set atendimentoAgressors = new HashSet(0);
	private Set historicoUsuarias = new HashSet(0);
	private Set objetoAgressaos = new HashSet(0);
	private Set tecnicos = new HashSet(0);
	private Set detalheViolencias = new HashSet(0);
	private Set anexos = new HashSet(0);
	private Set encaminhamentos = new HashSet(0);
	private Set violencias = new HashSet(0);
	private Set atendimentoFridas = new HashSet(0);
	private Set evolucaoAtendimentos = new HashSet(0);
	private Set historicoTransferencias = new HashSet(0);

	public Atendimento() {
	}

	public Atendimento(long id, AgendaAtendimento agendaAtendimento, Centro centro, Usuaria usuaria, Date dataCadastro,
			int status, long usuario) {
		this.id = id;
		this.agendaAtendimento = agendaAtendimento;
		this.centro = centro;
		this.usuaria = usuaria;
		this.dataCadastro = dataCadastro;
		this.status = status;
		this.usuario = usuario;
	}

	public Atendimento(long id, AgendaAtendimento agendaAtendimento, Centro centro, ClassificacaoCaso classificacaoCaso,
			Endereco endereco, LocalInternacao localInternacao, LocalOcorrencia localOcorrencia,
			PreAcolhimento preAcolhimento, SituacaoCaso situacaoCaso, Tecnico tecnico, UnidadeTempo unidadeTempo,
			Usuaria usuaria, Date dataCadastro, Date dataOcorrencia, Integer tempoUltimaViolencia,
			Integer recorreuServicoAtendimento, Integer realizouDenuncia, String resultadoDenuncia,
			String dificuldadeEncontradaDenuncia, String descricaoCaso, String providenciaTomada,
			Integer planoSeguranca, String medidasPlanoSeguranca, String motivoDesligamento, Date dataDesligamento,
			int status, long usuario, Integer situacaoUsuaria, Integer sofreAmeacaMorte, Integer valTempoViolencia,
			Double valTempoViolenciaUb, Integer riscoIntegridadeFisica, Integer periodoOcorrencia,
			Long idTecnicoCriacao, Long idTecnicoAlteracao, Date dataCriacao, Date dataAlteracao, String horaOcorrencia,
			Integer vitimaFicouInternada, Integer valTempoInternacao, String localInternacao_1, String agravantes,
			Integer tipoEvento, String numeroBo, Date dataFormulario, String evolucao, Integer frida,
			Set atendimentoAgressors, Set historicoUsuarias, Set objetoAgressaos, Set tecnicos, Set detalheViolencias,
			Set anexos, Set encaminhamentos, Set violencias, Set atendimentoFridas, Set evolucaoAtendimentos,
			Set historicoTransferencias) {
		this.id = id;
		this.agendaAtendimento = agendaAtendimento;
		this.centro = centro;
		this.classificacaoCaso = classificacaoCaso;
		this.endereco = endereco;
		this.localInternacao = localInternacao;
		this.localOcorrencia = localOcorrencia;
		this.preAcolhimento = preAcolhimento;
		this.situacaoCaso = situacaoCaso;
		this.tecnico = tecnico;
		this.unidadeTempo = unidadeTempo;
		this.usuaria = usuaria;
		this.dataCadastro = dataCadastro;
		this.dataOcorrencia = dataOcorrencia;
		this.tempoUltimaViolencia = tempoUltimaViolencia;
		this.recorreuServicoAtendimento = recorreuServicoAtendimento;
		this.realizouDenuncia = realizouDenuncia;
		this.resultadoDenuncia = resultadoDenuncia;
		this.dificuldadeEncontradaDenuncia = dificuldadeEncontradaDenuncia;
		this.descricaoCaso = descricaoCaso;
		this.providenciaTomada = providenciaTomada;
		this.planoSeguranca = planoSeguranca;
		this.medidasPlanoSeguranca = medidasPlanoSeguranca;
		this.motivoDesligamento = motivoDesligamento;
		this.dataDesligamento = dataDesligamento;
		this.status = status;
		this.usuario = usuario;
		this.situacaoUsuaria = situacaoUsuaria;
		this.sofreAmeacaMorte = sofreAmeacaMorte;
		this.valTempoViolencia = valTempoViolencia;
		this.valTempoViolenciaUb = valTempoViolenciaUb;
		this.riscoIntegridadeFisica = riscoIntegridadeFisica;
		this.periodoOcorrencia = periodoOcorrencia;
		this.idTecnicoCriacao = idTecnicoCriacao;
		this.idTecnicoAlteracao = idTecnicoAlteracao;
		this.dataCriacao = dataCriacao;
		this.dataAlteracao = dataAlteracao;
		this.horaOcorrencia = horaOcorrencia;
		this.vitimaFicouInternada = vitimaFicouInternada;
		this.valTempoInternacao = valTempoInternacao;
		this.localInternacao_1 = localInternacao_1;
		this.agravantes = agravantes;
		this.tipoEvento = tipoEvento;
		this.numeroBo = numeroBo;
		this.dataFormulario = dataFormulario;
		this.evolucao = evolucao;
		this.frida = frida;
		this.atendimentoAgressors = atendimentoAgressors;
		this.historicoUsuarias = historicoUsuarias;
		this.objetoAgressaos = objetoAgressaos;
		this.tecnicos = tecnicos;
		this.detalheViolencias = detalheViolencias;
		this.anexos = anexos;
		this.encaminhamentos = encaminhamentos;
		this.violencias = violencias;
		this.atendimentoFridas = atendimentoFridas;
		this.evolucaoAtendimentos = evolucaoAtendimentos;
		this.historicoTransferencias = historicoTransferencias;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_agenda_atendimento", nullable = false)
	public AgendaAtendimento getAgendaAtendimento() {
		return this.agendaAtendimento;
	}

	public void setAgendaAtendimento(AgendaAtendimento agendaAtendimento) {
		this.agendaAtendimento = agendaAtendimento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_centro", nullable = false)
	public Centro getCentro() {
		return this.centro;
	}

	public void setCentro(Centro centro) {
		this.centro = centro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_classificacao_caso")
	public ClassificacaoCaso getClassificacaoCaso() {
		return this.classificacaoCaso;
	}

	public void setClassificacaoCaso(ClassificacaoCaso classificacaoCaso) {
		this.classificacaoCaso = classificacaoCaso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_endereco")
	public Endereco getEndereco() {
		return this.endereco;
	}

	public void setEndereco(Endereco endereco) {
		this.endereco = endereco;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_local_internacao")
	public LocalInternacao getLocalInternacao() {
		return this.localInternacao;
	}

	public void setLocalInternacao(LocalInternacao localInternacao) {
		this.localInternacao = localInternacao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_local_ocorrencia")
	public LocalOcorrencia getLocalOcorrencia() {
		return this.localOcorrencia;
	}

	public void setLocalOcorrencia(LocalOcorrencia localOcorrencia) {
		this.localOcorrencia = localOcorrencia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_pre_acolhimento")
	public PreAcolhimento getPreAcolhimento() {
		return this.preAcolhimento;
	}

	public void setPreAcolhimento(PreAcolhimento preAcolhimento) {
		this.preAcolhimento = preAcolhimento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_situacao_caso")
	public SituacaoCaso getSituacaoCaso() {
		return this.situacaoCaso;
	}

	public void setSituacaoCaso(SituacaoCaso situacaoCaso) {
		this.situacaoCaso = situacaoCaso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tecnico_desligamento")
	public Tecnico getTecnico() {
		return this.tecnico;
	}

	public void setTecnico(Tecnico tecnico) {
		this.tecnico = tecnico;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_unidade_tempo")
	public UnidadeTempo getUnidadeTempo() {
		return this.unidadeTempo;
	}

	public void setUnidadeTempo(UnidadeTempo unidadeTempo) {
		this.unidadeTempo = unidadeTempo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuaria", nullable = false)
	public Usuaria getUsuaria() {
		return this.usuaria;
	}

	public void setUsuaria(Usuaria usuaria) {
		this.usuaria = usuaria;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_cadastro", nullable = false, length = 29)
	public Date getDataCadastro() {
		return this.dataCadastro;
	}

	public void setDataCadastro(Date dataCadastro) {
		this.dataCadastro = dataCadastro;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data_ocorrencia", length = 13)
	public Date getDataOcorrencia() {
		return this.dataOcorrencia;
	}

	public void setDataOcorrencia(Date dataOcorrencia) {
		this.dataOcorrencia = dataOcorrencia;
	}

	@Column(name = "tempo_ultima_violencia")
	public Integer getTempoUltimaViolencia() {
		return this.tempoUltimaViolencia;
	}

	public void setTempoUltimaViolencia(Integer tempoUltimaViolencia) {
		this.tempoUltimaViolencia = tempoUltimaViolencia;
	}

	@Column(name = "recorreu_servico_atendimento")
	public Integer getRecorreuServicoAtendimento() {
		return this.recorreuServicoAtendimento;
	}

	public void setRecorreuServicoAtendimento(Integer recorreuServicoAtendimento) {
		this.recorreuServicoAtendimento = recorreuServicoAtendimento;
	}

	@Column(name = "realizou_denuncia")
	public Integer getRealizouDenuncia() {
		return this.realizouDenuncia;
	}

	public void setRealizouDenuncia(Integer realizouDenuncia) {
		this.realizouDenuncia = realizouDenuncia;
	}

	@Column(name = "resultado_denuncia")
	public String getResultadoDenuncia() {
		return this.resultadoDenuncia;
	}

	public void setResultadoDenuncia(String resultadoDenuncia) {
		this.resultadoDenuncia = resultadoDenuncia;
	}

	@Column(name = "dificuldade_encontrada_denuncia")
	public String getDificuldadeEncontradaDenuncia() {
		return this.dificuldadeEncontradaDenuncia;
	}

	public void setDificuldadeEncontradaDenuncia(String dificuldadeEncontradaDenuncia) {
		this.dificuldadeEncontradaDenuncia = dificuldadeEncontradaDenuncia;
	}

	@Column(name = "descricao_caso")
	public String getDescricaoCaso() {
		return this.descricaoCaso;
	}

	public void setDescricaoCaso(String descricaoCaso) {
		this.descricaoCaso = descricaoCaso;
	}

	@Column(name = "providencia_tomada")
	public String getProvidenciaTomada() {
		return this.providenciaTomada;
	}

	public void setProvidenciaTomada(String providenciaTomada) {
		this.providenciaTomada = providenciaTomada;
	}

	@Column(name = "plano_seguranca")
	public Integer getPlanoSeguranca() {
		return this.planoSeguranca;
	}

	public void setPlanoSeguranca(Integer planoSeguranca) {
		this.planoSeguranca = planoSeguranca;
	}

	@Column(name = "medidas_plano_seguranca")
	public String getMedidasPlanoSeguranca() {
		return this.medidasPlanoSeguranca;
	}

	public void setMedidasPlanoSeguranca(String medidasPlanoSeguranca) {
		this.medidasPlanoSeguranca = medidasPlanoSeguranca;
	}

	@Column(name = "motivo_desligamento")
	public String getMotivoDesligamento() {
		return this.motivoDesligamento;
	}

	public void setMotivoDesligamento(String motivoDesligamento) {
		this.motivoDesligamento = motivoDesligamento;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_desligamento", length = 29)
	public Date getDataDesligamento() {
		return this.dataDesligamento;
	}

	public void setDataDesligamento(Date dataDesligamento) {
		this.dataDesligamento = dataDesligamento;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "usuario", nullable = false)
	public long getUsuario() {
		return this.usuario;
	}

	public void setUsuario(long usuario) {
		this.usuario = usuario;
	}

	@Column(name = "situacao_usuaria")
	public Integer getSituacaoUsuaria() {
		return this.situacaoUsuaria;
	}

	public void setSituacaoUsuaria(Integer situacaoUsuaria) {
		this.situacaoUsuaria = situacaoUsuaria;
	}

	@Column(name = "sofre_ameaca_morte")
	public Integer getSofreAmeacaMorte() {
		return this.sofreAmeacaMorte;
	}

	public void setSofreAmeacaMorte(Integer sofreAmeacaMorte) {
		this.sofreAmeacaMorte = sofreAmeacaMorte;
	}

	@Column(name = "val_tempo_violencia")
	public Integer getValTempoViolencia() {
		return this.valTempoViolencia;
	}

	public void setValTempoViolencia(Integer valTempoViolencia) {
		this.valTempoViolencia = valTempoViolencia;
	}

	@Column(name = "val_tempo_violencia_ub", precision = 17, scale = 17)
	public Double getValTempoViolenciaUb() {
		return this.valTempoViolenciaUb;
	}

	public void setValTempoViolenciaUb(Double valTempoViolenciaUb) {
		this.valTempoViolenciaUb = valTempoViolenciaUb;
	}

	@Column(name = "risco_integridade_fisica")
	public Integer getRiscoIntegridadeFisica() {
		return this.riscoIntegridadeFisica;
	}

	public void setRiscoIntegridadeFisica(Integer riscoIntegridadeFisica) {
		this.riscoIntegridadeFisica = riscoIntegridadeFisica;
	}

	@Column(name = "periodo_ocorrencia")
	public Integer getPeriodoOcorrencia() {
		return this.periodoOcorrencia;
	}

	public void setPeriodoOcorrencia(Integer periodoOcorrencia) {
		this.periodoOcorrencia = periodoOcorrencia;
	}

	@Column(name = "id_tecnico_criacao")
	public Long getIdTecnicoCriacao() {
		return this.idTecnicoCriacao;
	}

	public void setIdTecnicoCriacao(Long idTecnicoCriacao) {
		this.idTecnicoCriacao = idTecnicoCriacao;
	}

	@Column(name = "id_tecnico_alteracao")
	public Long getIdTecnicoAlteracao() {
		return this.idTecnicoAlteracao;
	}

	public void setIdTecnicoAlteracao(Long idTecnicoAlteracao) {
		this.idTecnicoAlteracao = idTecnicoAlteracao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_criacao", length = 29)
	public Date getDataCriacao() {
		return this.dataCriacao;
	}

	public void setDataCriacao(Date dataCriacao) {
		this.dataCriacao = dataCriacao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_alteracao", length = 29)
	public Date getDataAlteracao() {
		return this.dataAlteracao;
	}

	public void setDataAlteracao(Date dataAlteracao) {
		this.dataAlteracao = dataAlteracao;
	}

	@Column(name = "hora_ocorrencia", length = 6)
	public String getHoraOcorrencia() {
		return this.horaOcorrencia;
	}

	public void setHoraOcorrencia(String horaOcorrencia) {
		this.horaOcorrencia = horaOcorrencia;
	}

	@Column(name = "vitima_ficou_internada")
	public Integer getVitimaFicouInternada() {
		return this.vitimaFicouInternada;
	}

	public void setVitimaFicouInternada(Integer vitimaFicouInternada) {
		this.vitimaFicouInternada = vitimaFicouInternada;
	}

	@Column(name = "val_tempo_internacao")
	public Integer getValTempoInternacao() {
		return this.valTempoInternacao;
	}

	public void setValTempoInternacao(Integer valTempoInternacao) {
		this.valTempoInternacao = valTempoInternacao;
	}

	@Column(name = "local_internacao", length = 100)
	public String getLocalInternacao_1() {
		return this.localInternacao_1;
	}

	public void setLocalInternacao_1(String localInternacao_1) {
		this.localInternacao_1 = localInternacao_1;
	}

	@Column(name = "agravantes")
	public String getAgravantes() {
		return this.agravantes;
	}

	public void setAgravantes(String agravantes) {
		this.agravantes = agravantes;
	}

	@Column(name = "tipo_evento")
	public Integer getTipoEvento() {
		return this.tipoEvento;
	}

	public void setTipoEvento(Integer tipoEvento) {
		this.tipoEvento = tipoEvento;
	}

	@Column(name = "numero_bo", unique = true, length = 100)
	public String getNumeroBo() {
		return this.numeroBo;
	}

	public void setNumeroBo(String numeroBo) {
		this.numeroBo = numeroBo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data_formulario", length = 13)
	public Date getDataFormulario() {
		return this.dataFormulario;
	}

	public void setDataFormulario(Date dataFormulario) {
		this.dataFormulario = dataFormulario;
	}

	@Column(name = "evolucao")
	public String getEvolucao() {
		return this.evolucao;
	}

	public void setEvolucao(String evolucao) {
		this.evolucao = evolucao;
	}

	@Column(name = "frida")
	public Integer getFrida() {
		return this.frida;
	}

	public void setFrida(Integer frida) {
		this.frida = frida;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "atendimento")
	public Set getAtendimentoAgressors() {
		return this.atendimentoAgressors;
	}

	public void setAtendimentoAgressors(Set atendimentoAgressors) {
		this.atendimentoAgressors = atendimentoAgressors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "atendimento")
	public Set getHistoricoUsuarias() {
		return this.historicoUsuarias;
	}

	public void setHistoricoUsuarias(Set historicoUsuarias) {
		this.historicoUsuarias = historicoUsuarias;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "atendimento_objeto_agressao", joinColumns = {
			@JoinColumn(name = "id_atendimento", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "id_objeto_agressao", nullable = false, updatable = false) })
	public Set getObjetoAgressaos() {
		return this.objetoAgressaos;
	}

	public void setObjetoAgressaos(Set objetoAgressaos) {
		this.objetoAgressaos = objetoAgressaos;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "atendimento_tecnico", joinColumns = {
			@JoinColumn(name = "id_atendimento", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "id_tecnico", nullable = false, updatable = false) })
	public Set getTecnicos() {
		return this.tecnicos;
	}

	public void setTecnicos(Set tecnicos) {
		this.tecnicos = tecnicos;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "atendimento_detalhe_violencia", joinColumns = {
			@JoinColumn(name = "id_atendimento", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "id_detalhe_violencia", nullable = false, updatable = false) })
	public Set getDetalheViolencias() {
		return this.detalheViolencias;
	}

	public void setDetalheViolencias(Set detalheViolencias) {
		this.detalheViolencias = detalheViolencias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "atendimento")
	public Set getAnexos() {
		return this.anexos;
	}

	public void setAnexos(Set anexos) {
		this.anexos = anexos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "atendimento")
	public Set getEncaminhamentos() {
		return this.encaminhamentos;
	}

	public void setEncaminhamentos(Set encaminhamentos) {
		this.encaminhamentos = encaminhamentos;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "atendimento_violencia", joinColumns = {
			@JoinColumn(name = "id_atendimento", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "id_violencia", nullable = false, updatable = false) })
	public Set getViolencias() {
		return this.violencias;
	}

	public void setViolencias(Set violencias) {
		this.violencias = violencias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "atendimento")
	public Set getAtendimentoFridas() {
		return this.atendimentoFridas;
	}

	public void setAtendimentoFridas(Set atendimentoFridas) {
		this.atendimentoFridas = atendimentoFridas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "atendimento")
	public Set getEvolucaoAtendimentos() {
		return this.evolucaoAtendimentos;
	}

	public void setEvolucaoAtendimentos(Set evolucaoAtendimentos) {
		this.evolucaoAtendimentos = evolucaoAtendimentos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "atendimento")
	public Set getHistoricoTransferencias() {
		return this.historicoTransferencias;
	}

	public void setHistoricoTransferencias(Set historicoTransferencias) {
		this.historicoTransferencias = historicoTransferencias;
	}

}
