package br.gov.pa.prodepa;
// Generated Nov 1, 2019 4:29:22 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AtendimentoFridaRespotas generated by hbm2java
 */
@Entity
@Table(name = "atendimento_frida_respotas")
public class AtendimentoFridaResposta implements java.io.Serializable {

	private long idAtendimentoFridaRespotas;
	private FridaPerguntas fridaPerguntas;
	private FridaSubresposta fridaSubresposta;
	private int idAtendimentoFrida;
	private Integer resposta;

	public AtendimentoFridaResposta() {
	}

	public AtendimentoFridaResposta(long idAtendimentoFridaRespotas, FridaPerguntas fridaPerguntas,
			int idAtendimentoFrida) {
		this.idAtendimentoFridaRespotas = idAtendimentoFridaRespotas;
		this.fridaPerguntas = fridaPerguntas;
		this.idAtendimentoFrida = idAtendimentoFrida;
	}

	public AtendimentoFridaResposta(long idAtendimentoFridaRespotas, FridaPerguntas fridaPerguntas,
			FridaSubresposta fridaSubresposta, int idAtendimentoFrida, Integer resposta) {
		this.idAtendimentoFridaRespotas = idAtendimentoFridaRespotas;
		this.fridaPerguntas = fridaPerguntas;
		this.fridaSubresposta = fridaSubresposta;
		this.idAtendimentoFrida = idAtendimentoFrida;
		this.resposta = resposta;
	}

	@Id

	@Column(name = "id_atendimento_frida_respotas", unique = true, nullable = false)
	public long getIdAtendimentoFridaRespotas() {
		return this.idAtendimentoFridaRespotas;
	}

	public void setIdAtendimentoFridaRespotas(long idAtendimentoFridaRespotas) {
		this.idAtendimentoFridaRespotas = idAtendimentoFridaRespotas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_pergunta", nullable = false)
	public FridaPerguntas getFridaPerguntas() {
		return this.fridaPerguntas;
	}

	public void setFridaPerguntas(FridaPerguntas fridaPerguntas) {
		this.fridaPerguntas = fridaPerguntas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_subresposta")
	public FridaSubresposta getFridaSubresposta() {
		return this.fridaSubresposta;
	}

	public void setFridaSubresposta(FridaSubresposta fridaSubresposta) {
		this.fridaSubresposta = fridaSubresposta;
	}

	@Column(name = "Id_atendimento_frida", nullable = false)
	public int getIdAtendimentoFrida() {
		return this.idAtendimentoFrida;
	}

	public void setIdAtendimentoFrida(int idAtendimentoFrida) {
		this.idAtendimentoFrida = idAtendimentoFrida;
	}

	@Column(name = "resposta")
	public Integer getResposta() {
		return this.resposta;
	}

	public void setResposta(Integer resposta) {
		this.resposta = resposta;
	}

}
