package br.gov.pa.prodepa;
// Generated Nov 1, 2019 4:29:22 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AtendimentoAgressorId generated by hbm2java
 */
@Embeddable
public class AtendimentoAgressorId implements java.io.Serializable {

	private long idAtendimento;
	private long idAgressor;
	private long idGrauRelacao;

	public AtendimentoAgressorId() {
	}

	public AtendimentoAgressorId(long idAtendimento, long idAgressor, long idGrauRelacao) {
		this.idAtendimento = idAtendimento;
		this.idAgressor = idAgressor;
		this.idGrauRelacao = idGrauRelacao;
	}

	@Column(name = "id_atendimento", nullable = false)
	public long getIdAtendimento() {
		return this.idAtendimento;
	}

	public void setIdAtendimento(long idAtendimento) {
		this.idAtendimento = idAtendimento;
	}

	@Column(name = "id_agressor", nullable = false)
	public long getIdAgressor() {
		return this.idAgressor;
	}

	public void setIdAgressor(long idAgressor) {
		this.idAgressor = idAgressor;
	}

	@Column(name = "id_grau_relacao", nullable = false)
	public long getIdGrauRelacao() {
		return this.idGrauRelacao;
	}

	public void setIdGrauRelacao(long idGrauRelacao) {
		this.idGrauRelacao = idGrauRelacao;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AtendimentoAgressorId))
			return false;
		AtendimentoAgressorId castOther = (AtendimentoAgressorId) other;

		return (this.getIdAtendimento() == castOther.getIdAtendimento())
				&& (this.getIdAgressor() == castOther.getIdAgressor())
				&& (this.getIdGrauRelacao() == castOther.getIdGrauRelacao());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdAtendimento();
		result = 37 * result + (int) this.getIdAgressor();
		result = 37 * result + (int) this.getIdGrauRelacao();
		return result;
	}

}
