package br.gov.pa.prodepa;
// Generated Nov 1, 2019 4:29:22 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Centro generated by hbm2java
 */
@Entity
@Table(name = "centro")
public class Centro implements java.io.Serializable {

	private long id;
	private Coordenadoria coordenadoria;
	private String razaoSocial;
	private String email;
	private String cnpj;
	private String inscricaoEstadual;
	private String responsavel;
	private String cargo;
	private int situacao;
	private Set agendaTecnicos = new HashSet(0);
	private Set evolucaoAtendimentos = new HashSet(0);
	private Set historicoTransferenciasForIdCentroDestino = new HashSet(0);
	private Set historicoTransferenciasForIdCentroOrigem = new HashSet(0);
	private Set atendimentoVisitaDomiciliars = new HashSet(0);
	private Set enderecos = new HashSet(0);
	private Set atendimentos = new HashSet(0);
	private Set atendimentoGrupos = new HashSet(0);
	private Set agendaAtendimentos = new HashSet(0);
	private Set encaminhamentos = new HashSet(0);
	private Set tecnicoCentros = new HashSet(0);
	private Set preAcolhimentos = new HashSet(0);
	private Set centroMunicipios = new HashSet(0);
	private Set comunicados = new HashSet(0);

	public Centro() {
	}

	public Centro(long id, Coordenadoria coordenadoria, String razaoSocial, String cnpj, String responsavel,
			String cargo, int situacao) {
		this.id = id;
		this.coordenadoria = coordenadoria;
		this.razaoSocial = razaoSocial;
		this.cnpj = cnpj;
		this.responsavel = responsavel;
		this.cargo = cargo;
		this.situacao = situacao;
	}

	public Centro(long id, Coordenadoria coordenadoria, String razaoSocial, String email, String cnpj,
			String inscricaoEstadual, String responsavel, String cargo, int situacao, Set agendaTecnicos,
			Set evolucaoAtendimentos, Set historicoTransferenciasForIdCentroDestino,
			Set historicoTransferenciasForIdCentroOrigem, Set atendimentoVisitaDomiciliars, Set enderecos,
			Set atendimentos, Set atendimentoGrupos, Set agendaAtendimentos, Set encaminhamentos, Set tecnicoCentros,
			Set preAcolhimentos, Set centroMunicipios, Set comunicados) {
		this.id = id;
		this.coordenadoria = coordenadoria;
		this.razaoSocial = razaoSocial;
		this.email = email;
		this.cnpj = cnpj;
		this.inscricaoEstadual = inscricaoEstadual;
		this.responsavel = responsavel;
		this.cargo = cargo;
		this.situacao = situacao;
		this.agendaTecnicos = agendaTecnicos;
		this.evolucaoAtendimentos = evolucaoAtendimentos;
		this.historicoTransferenciasForIdCentroDestino = historicoTransferenciasForIdCentroDestino;
		this.historicoTransferenciasForIdCentroOrigem = historicoTransferenciasForIdCentroOrigem;
		this.atendimentoVisitaDomiciliars = atendimentoVisitaDomiciliars;
		this.enderecos = enderecos;
		this.atendimentos = atendimentos;
		this.atendimentoGrupos = atendimentoGrupos;
		this.agendaAtendimentos = agendaAtendimentos;
		this.encaminhamentos = encaminhamentos;
		this.tecnicoCentros = tecnicoCentros;
		this.preAcolhimentos = preAcolhimentos;
		this.centroMunicipios = centroMunicipios;
		this.comunicados = comunicados;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_coordenadoria", nullable = false)
	public Coordenadoria getCoordenadoria() {
		return this.coordenadoria;
	}

	public void setCoordenadoria(Coordenadoria coordenadoria) {
		this.coordenadoria = coordenadoria;
	}

	@Column(name = "razao_social", nullable = false)
	public String getRazaoSocial() {
		return this.razaoSocial;
	}

	public void setRazaoSocial(String razaoSocial) {
		this.razaoSocial = razaoSocial;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "cnpj", nullable = false, length = 18)
	public String getCnpj() {
		return this.cnpj;
	}

	public void setCnpj(String cnpj) {
		this.cnpj = cnpj;
	}

	@Column(name = "inscricao_estadual", length = 50)
	public String getInscricaoEstadual() {
		return this.inscricaoEstadual;
	}

	public void setInscricaoEstadual(String inscricaoEstadual) {
		this.inscricaoEstadual = inscricaoEstadual;
	}

	@Column(name = "responsavel", nullable = false)
	public String getResponsavel() {
		return this.responsavel;
	}

	public void setResponsavel(String responsavel) {
		this.responsavel = responsavel;
	}

	@Column(name = "cargo", nullable = false)
	public String getCargo() {
		return this.cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}

	@Column(name = "situacao", nullable = false)
	public int getSituacao() {
		return this.situacao;
	}

	public void setSituacao(int situacao) {
		this.situacao = situacao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "centro")
	public Set getAgendaTecnicos() {
		return this.agendaTecnicos;
	}

	public void setAgendaTecnicos(Set agendaTecnicos) {
		this.agendaTecnicos = agendaTecnicos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "centro")
	public Set getEvolucaoAtendimentos() {
		return this.evolucaoAtendimentos;
	}

	public void setEvolucaoAtendimentos(Set evolucaoAtendimentos) {
		this.evolucaoAtendimentos = evolucaoAtendimentos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "centroByIdCentroDestino")
	public Set getHistoricoTransferenciasForIdCentroDestino() {
		return this.historicoTransferenciasForIdCentroDestino;
	}

	public void setHistoricoTransferenciasForIdCentroDestino(Set historicoTransferenciasForIdCentroDestino) {
		this.historicoTransferenciasForIdCentroDestino = historicoTransferenciasForIdCentroDestino;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "centroByIdCentroOrigem")
	public Set getHistoricoTransferenciasForIdCentroOrigem() {
		return this.historicoTransferenciasForIdCentroOrigem;
	}

	public void setHistoricoTransferenciasForIdCentroOrigem(Set historicoTransferenciasForIdCentroOrigem) {
		this.historicoTransferenciasForIdCentroOrigem = historicoTransferenciasForIdCentroOrigem;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "centro")
	public Set getAtendimentoVisitaDomiciliars() {
		return this.atendimentoVisitaDomiciliars;
	}

	public void setAtendimentoVisitaDomiciliars(Set atendimentoVisitaDomiciliars) {
		this.atendimentoVisitaDomiciliars = atendimentoVisitaDomiciliars;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "centro")
	public Set getEnderecos() {
		return this.enderecos;
	}

	public void setEnderecos(Set enderecos) {
		this.enderecos = enderecos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "centro")
	public Set getAtendimentos() {
		return this.atendimentos;
	}

	public void setAtendimentos(Set atendimentos) {
		this.atendimentos = atendimentos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "centro")
	public Set getAtendimentoGrupos() {
		return this.atendimentoGrupos;
	}

	public void setAtendimentoGrupos(Set atendimentoGrupos) {
		this.atendimentoGrupos = atendimentoGrupos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "centro")
	public Set getAgendaAtendimentos() {
		return this.agendaAtendimentos;
	}

	public void setAgendaAtendimentos(Set agendaAtendimentos) {
		this.agendaAtendimentos = agendaAtendimentos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "centro")
	public Set getEncaminhamentos() {
		return this.encaminhamentos;
	}

	public void setEncaminhamentos(Set encaminhamentos) {
		this.encaminhamentos = encaminhamentos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "centro")
	public Set getTecnicoCentros() {
		return this.tecnicoCentros;
	}

	public void setTecnicoCentros(Set tecnicoCentros) {
		this.tecnicoCentros = tecnicoCentros;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "centro")
	public Set getPreAcolhimentos() {
		return this.preAcolhimentos;
	}

	public void setPreAcolhimentos(Set preAcolhimentos) {
		this.preAcolhimentos = preAcolhimentos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "centro")
	public Set getCentroMunicipios() {
		return this.centroMunicipios;
	}

	public void setCentroMunicipios(Set centroMunicipios) {
		this.centroMunicipios = centroMunicipios;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "comunicado_centro", joinColumns = {
			@JoinColumn(name = "id_centro", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "id_comunicado", nullable = false, updatable = false) })
	public Set getComunicados() {
		return this.comunicados;
	}

	public void setComunicados(Set comunicados) {
		this.comunicados = comunicados;
	}

}
