package br.gov.pa.prodepa;
// Generated Nov 1, 2019 4:29:22 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CentroMunicipio generated by hbm2java
 */
@Entity
@Table(name = "centro_municipio")
public class CentroMunicipio implements java.io.Serializable {

	private CentroMunicipioId id;
	private Centro centro;

	public CentroMunicipio() {
	}

	public CentroMunicipio(CentroMunicipioId id, Centro centro) {
		this.id = id;
		this.centro = centro;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idCentro", column = @Column(name = "id_centro", nullable = false)),
			@AttributeOverride(name = "idMunicipio", column = @Column(name = "id_municipio", nullable = false)) })
	public CentroMunicipioId getId() {
		return this.id;
	}

	public void setId(CentroMunicipioId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_centro", nullable = false, insertable = false, updatable = false)
	public Centro getCentro() {
		return this.centro;
	}

	public void setCentro(Centro centro) {
		this.centro = centro;
	}

}
