package br.gov.pa.prodepa;
// Generated Nov 1, 2019 4:29:22 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CentroMunicipioId generated by hbm2java
 */
@Embeddable
public class CentroMunicipioId implements java.io.Serializable {

	private long idCentro;
	private long idMunicipio;

	public CentroMunicipioId() {
	}

	public CentroMunicipioId(long idCentro, long idMunicipio) {
		this.idCentro = idCentro;
		this.idMunicipio = idMunicipio;
	}

	@Column(name = "id_centro", nullable = false)
	public long getIdCentro() {
		return this.idCentro;
	}

	public void setIdCentro(long idCentro) {
		this.idCentro = idCentro;
	}

	@Column(name = "id_municipio", nullable = false)
	public long getIdMunicipio() {
		return this.idMunicipio;
	}

	public void setIdMunicipio(long idMunicipio) {
		this.idMunicipio = idMunicipio;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CentroMunicipioId))
			return false;
		CentroMunicipioId castOther = (CentroMunicipioId) other;

		return (this.getIdCentro() == castOther.getIdCentro()) && (this.getIdMunicipio() == castOther.getIdMunicipio());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdCentro();
		result = 37 * result + (int) this.getIdMunicipio();
		return result;
	}

}
