package br.gov.pa.prodepa;
// Generated Nov 1, 2019 4:29:22 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Documentos generated by hbm2java
 */
@Entity
@Table(name = "documentos")
public class Documentos implements java.io.Serializable {

	private long id;
	private String descricao;
	private int situacao;
	private Set usuarias = new HashSet(0);

	public Documentos() {
	}

	public Documentos(long id, String descricao, int situacao) {
		this.id = id;
		this.descricao = descricao;
		this.situacao = situacao;
	}

	public Documentos(long id, String descricao, int situacao, Set usuarias) {
		this.id = id;
		this.descricao = descricao;
		this.situacao = situacao;
		this.usuarias = usuarias;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "descricao", nullable = false)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "situacao", nullable = false)
	public int getSituacao() {
		return this.situacao;
	}

	public void setSituacao(int situacao) {
		this.situacao = situacao;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "documentos_usuaria", joinColumns = {
			@JoinColumn(name = "id_documentos", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "id_usuaria", nullable = false, updatable = false) })
	public Set getUsuarias() {
		return this.usuarias;
	}

	public void setUsuarias(Set usuarias) {
		this.usuarias = usuarias;
	}

}
