package br.gov.pa.prodepa;
// Generated Nov 1, 2019 4:29:22 PM by Hibernate Tools 5.2.12.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Endereco generated by hbm2java
 */
@Entity
@Table(name = "endereco")
public class Endereco implements java.io.Serializable {

	private long id;
	private Agressor agressor;
	private Centro centro;
	private GrauRelacao grauRelacao;
	private Regiao regiao;
	private Usuaria usuaria;
	private String logradouro;
	private String complemento;
	private String cep;
	private String bairro;
	private long idEstado;
	private long idMunicipio;
	private int situacao;
	private String telefone1;
	private String telefone2;
	private Integer tipoEndereco;
	private String proprietario;
	private Double longitude;
	private Double latitude;
	private String numero;
	private String distrito;
	private Integer zona;
	private Serializable geoTerritorio;
	private Set atendimentos = new HashSet(0);

	public Endereco() {
	}

	public Endereco(long id, String logradouro, long idEstado, long idMunicipio, int situacao) {
		this.id = id;
		this.logradouro = logradouro;
		this.idEstado = idEstado;
		this.idMunicipio = idMunicipio;
		this.situacao = situacao;
	}

	public Endereco(long id, Agressor agressor, Centro centro, GrauRelacao grauRelacao, Regiao regiao, Usuaria usuaria,
			String logradouro, String complemento, String cep, String bairro, long idEstado, long idMunicipio,
			int situacao, String telefone1, String telefone2, Integer tipoEndereco, String proprietario,
			Double longitude, Double latitude, String numero, String distrito, Integer zona, Serializable geoTerritorio,
			Set atendimentos) {
		this.id = id;
		this.agressor = agressor;
		this.centro = centro;
		this.grauRelacao = grauRelacao;
		this.regiao = regiao;
		this.usuaria = usuaria;
		this.logradouro = logradouro;
		this.complemento = complemento;
		this.cep = cep;
		this.bairro = bairro;
		this.idEstado = idEstado;
		this.idMunicipio = idMunicipio;
		this.situacao = situacao;
		this.telefone1 = telefone1;
		this.telefone2 = telefone2;
		this.tipoEndereco = tipoEndereco;
		this.proprietario = proprietario;
		this.longitude = longitude;
		this.latitude = latitude;
		this.numero = numero;
		this.distrito = distrito;
		this.zona = zona;
		this.geoTerritorio = geoTerritorio;
		this.atendimentos = atendimentos;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_agressor")
	public Agressor getAgressor() {
		return this.agressor;
	}

	public void setAgressor(Agressor agressor) {
		this.agressor = agressor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_centro")
	public Centro getCentro() {
		return this.centro;
	}

	public void setCentro(Centro centro) {
		this.centro = centro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_grau_relacao")
	public GrauRelacao getGrauRelacao() {
		return this.grauRelacao;
	}

	public void setGrauRelacao(GrauRelacao grauRelacao) {
		this.grauRelacao = grauRelacao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_regiao")
	public Regiao getRegiao() {
		return this.regiao;
	}

	public void setRegiao(Regiao regiao) {
		this.regiao = regiao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuaria")
	public Usuaria getUsuaria() {
		return this.usuaria;
	}

	public void setUsuaria(Usuaria usuaria) {
		this.usuaria = usuaria;
	}

	@Column(name = "logradouro", nullable = false, length = 125)
	public String getLogradouro() {
		return this.logradouro;
	}

	public void setLogradouro(String logradouro) {
		this.logradouro = logradouro;
	}

	@Column(name = "complemento")
	public String getComplemento() {
		return this.complemento;
	}

	public void setComplemento(String complemento) {
		this.complemento = complemento;
	}

	@Column(name = "cep", length = 10)
	public String getCep() {
		return this.cep;
	}

	public void setCep(String cep) {
		this.cep = cep;
	}

	@Column(name = "bairro")
	public String getBairro() {
		return this.bairro;
	}

	public void setBairro(String bairro) {
		this.bairro = bairro;
	}

	@Column(name = "id_estado", nullable = false)
	public long getIdEstado() {
		return this.idEstado;
	}

	public void setIdEstado(long idEstado) {
		this.idEstado = idEstado;
	}

	@Column(name = "id_municipio", nullable = false)
	public long getIdMunicipio() {
		return this.idMunicipio;
	}

	public void setIdMunicipio(long idMunicipio) {
		this.idMunicipio = idMunicipio;
	}

	@Column(name = "situacao", nullable = false)
	public int getSituacao() {
		return this.situacao;
	}

	public void setSituacao(int situacao) {
		this.situacao = situacao;
	}

	@Column(name = "telefone_1", length = 50)
	public String getTelefone1() {
		return this.telefone1;
	}

	public void setTelefone1(String telefone1) {
		this.telefone1 = telefone1;
	}

	@Column(name = "telefone_2", length = 50)
	public String getTelefone2() {
		return this.telefone2;
	}

	public void setTelefone2(String telefone2) {
		this.telefone2 = telefone2;
	}

	@Column(name = "tipo_endereco")
	public Integer getTipoEndereco() {
		return this.tipoEndereco;
	}

	public void setTipoEndereco(Integer tipoEndereco) {
		this.tipoEndereco = tipoEndereco;
	}

	@Column(name = "proprietario")
	public String getProprietario() {
		return this.proprietario;
	}

	public void setProprietario(String proprietario) {
		this.proprietario = proprietario;
	}

	@Column(name = "longitude", precision = 17, scale = 17)
	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	@Column(name = "latitude", precision = 17, scale = 17)
	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	@Column(name = "numero", length = 10)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Column(name = "distrito", length = 200)
	public String getDistrito() {
		return this.distrito;
	}

	public void setDistrito(String distrito) {
		this.distrito = distrito;
	}

	@Column(name = "zona")
	public Integer getZona() {
		return this.zona;
	}

	public void setZona(Integer zona) {
		this.zona = zona;
	}

	@Column(name = "geo_territorio")
	public Serializable getGeoTerritorio() {
		return this.geoTerritorio;
	}

	public void setGeoTerritorio(Serializable geoTerritorio) {
		this.geoTerritorio = geoTerritorio;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "endereco")
	public Set getAtendimentos() {
		return this.atendimentos;
	}

	public void setAtendimentos(Set atendimentos) {
		this.atendimentos = atendimentos;
	}

}
