package br.gov.pa.prodepa;
// Generated Nov 1, 2019 4:29:22 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EvolucaoAtendimento generated by hbm2java
 */
@Entity
@Table(name = "evolucao_atendimento")
public class EvolucaoAtendimento implements java.io.Serializable {

	private long id;
	private AgendaAtendimento agendaAtendimento;
	private Atendimento atendimento;
	private Centro centro;
	private Tecnico tecnico;
	private long numero;
	private Date dataCadastro;
	private String observacaoTecnica;
	private long usuario;
	private Date dataEvolucao;
	private String nomeFamiliar;
	private Date dataNascimento;
	private Integer nivelEscolaridade;
	private long tipoEvolucao;
	private Long grauRelacao;
	private String relatoPsicologico;
	private Set historicoUsuarias = new HashSet(0);

	public EvolucaoAtendimento() {
	}

	public EvolucaoAtendimento(long id, AgendaAtendimento agendaAtendimento, Atendimento atendimento, Centro centro,
			Tecnico tecnico, long numero, Date dataCadastro, String observacaoTecnica, long usuario, Date dataEvolucao,
			long tipoEvolucao) {
		this.id = id;
		this.agendaAtendimento = agendaAtendimento;
		this.atendimento = atendimento;
		this.centro = centro;
		this.tecnico = tecnico;
		this.numero = numero;
		this.dataCadastro = dataCadastro;
		this.observacaoTecnica = observacaoTecnica;
		this.usuario = usuario;
		this.dataEvolucao = dataEvolucao;
		this.tipoEvolucao = tipoEvolucao;
	}

	public EvolucaoAtendimento(long id, AgendaAtendimento agendaAtendimento, Atendimento atendimento, Centro centro,
			Tecnico tecnico, long numero, Date dataCadastro, String observacaoTecnica, long usuario, Date dataEvolucao,
			String nomeFamiliar, Date dataNascimento, Integer nivelEscolaridade, long tipoEvolucao, Long grauRelacao,
			String relatoPsicologico, Set historicoUsuarias) {
		this.id = id;
		this.agendaAtendimento = agendaAtendimento;
		this.atendimento = atendimento;
		this.centro = centro;
		this.tecnico = tecnico;
		this.numero = numero;
		this.dataCadastro = dataCadastro;
		this.observacaoTecnica = observacaoTecnica;
		this.usuario = usuario;
		this.dataEvolucao = dataEvolucao;
		this.nomeFamiliar = nomeFamiliar;
		this.dataNascimento = dataNascimento;
		this.nivelEscolaridade = nivelEscolaridade;
		this.tipoEvolucao = tipoEvolucao;
		this.grauRelacao = grauRelacao;
		this.relatoPsicologico = relatoPsicologico;
		this.historicoUsuarias = historicoUsuarias;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_agenda_atendimento", nullable = false)
	public AgendaAtendimento getAgendaAtendimento() {
		return this.agendaAtendimento;
	}

	public void setAgendaAtendimento(AgendaAtendimento agendaAtendimento) {
		this.agendaAtendimento = agendaAtendimento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_atendimento", nullable = false)
	public Atendimento getAtendimento() {
		return this.atendimento;
	}

	public void setAtendimento(Atendimento atendimento) {
		this.atendimento = atendimento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_centro", nullable = false)
	public Centro getCentro() {
		return this.centro;
	}

	public void setCentro(Centro centro) {
		this.centro = centro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tecnico", nullable = false)
	public Tecnico getTecnico() {
		return this.tecnico;
	}

	public void setTecnico(Tecnico tecnico) {
		this.tecnico = tecnico;
	}

	@Column(name = "numero", nullable = false)
	public long getNumero() {
		return this.numero;
	}

	public void setNumero(long numero) {
		this.numero = numero;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_cadastro", nullable = false, length = 29)
	public Date getDataCadastro() {
		return this.dataCadastro;
	}

	public void setDataCadastro(Date dataCadastro) {
		this.dataCadastro = dataCadastro;
	}

	@Column(name = "observacao_tecnica", nullable = false)
	public String getObservacaoTecnica() {
		return this.observacaoTecnica;
	}

	public void setObservacaoTecnica(String observacaoTecnica) {
		this.observacaoTecnica = observacaoTecnica;
	}

	@Column(name = "usuario", nullable = false)
	public long getUsuario() {
		return this.usuario;
	}

	public void setUsuario(long usuario) {
		this.usuario = usuario;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data_evolucao", nullable = false, length = 13)
	public Date getDataEvolucao() {
		return this.dataEvolucao;
	}

	public void setDataEvolucao(Date dataEvolucao) {
		this.dataEvolucao = dataEvolucao;
	}

	@Column(name = "nome_familiar")
	public String getNomeFamiliar() {
		return this.nomeFamiliar;
	}

	public void setNomeFamiliar(String nomeFamiliar) {
		this.nomeFamiliar = nomeFamiliar;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data_nascimento", length = 13)
	public Date getDataNascimento() {
		return this.dataNascimento;
	}

	public void setDataNascimento(Date dataNascimento) {
		this.dataNascimento = dataNascimento;
	}

	@Column(name = "nivel_escolaridade")
	public Integer getNivelEscolaridade() {
		return this.nivelEscolaridade;
	}

	public void setNivelEscolaridade(Integer nivelEscolaridade) {
		this.nivelEscolaridade = nivelEscolaridade;
	}

	@Column(name = "tipo_evolucao", nullable = false)
	public long getTipoEvolucao() {
		return this.tipoEvolucao;
	}

	public void setTipoEvolucao(long tipoEvolucao) {
		this.tipoEvolucao = tipoEvolucao;
	}

	@Column(name = "grau_relacao")
	public Long getGrauRelacao() {
		return this.grauRelacao;
	}

	public void setGrauRelacao(Long grauRelacao) {
		this.grauRelacao = grauRelacao;
	}

	@Column(name = "relato_psicologico")
	public String getRelatoPsicologico() {
		return this.relatoPsicologico;
	}

	public void setRelatoPsicologico(String relatoPsicologico) {
		this.relatoPsicologico = relatoPsicologico;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "evolucaoAtendimento")
	public Set getHistoricoUsuarias() {
		return this.historicoUsuarias;
	}

	public void setHistoricoUsuarias(Set historicoUsuarias) {
		this.historicoUsuarias = historicoUsuarias;
	}

}
