package br.gov.pa.prodepa;
// Generated Nov 1, 2019 4:29:22 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FormularioCapa generated by hbm2java
 */
@Entity
@Table(name = "formulario_capa")
public class FormularioCapa implements java.io.Serializable {

	private long idFormulario;
	private FormularioOrientacao formularioOrientacao;
	private Long idUsuaria;
	private Date dataInclusao;
	private Date dataAlteracao;
	private Date dataExclusao;
	private Date dataConclusao;
	private Long idTecnicoInclusao;
	private Long idTecnicoAlteracao;
	private Long idTecnicoExclusao;
	private Long idTecnicoConclusao;
	private long idAtendimento;
	private Long idModelo;
	private Set formularioItems = new HashSet(0);

	public FormularioCapa() {
	}

	public FormularioCapa(long idFormulario, long idAtendimento) {
		this.idFormulario = idFormulario;
		this.idAtendimento = idAtendimento;
	}

	public FormularioCapa(long idFormulario, FormularioOrientacao formularioOrientacao, Long idUsuaria,
			Date dataInclusao, Date dataAlteracao, Date dataExclusao, Date dataConclusao, Long idTecnicoInclusao,
			Long idTecnicoAlteracao, Long idTecnicoExclusao, Long idTecnicoConclusao, long idAtendimento, Long idModelo,
			Set formularioItems) {
		this.idFormulario = idFormulario;
		this.formularioOrientacao = formularioOrientacao;
		this.idUsuaria = idUsuaria;
		this.dataInclusao = dataInclusao;
		this.dataAlteracao = dataAlteracao;
		this.dataExclusao = dataExclusao;
		this.dataConclusao = dataConclusao;
		this.idTecnicoInclusao = idTecnicoInclusao;
		this.idTecnicoAlteracao = idTecnicoAlteracao;
		this.idTecnicoExclusao = idTecnicoExclusao;
		this.idTecnicoConclusao = idTecnicoConclusao;
		this.idAtendimento = idAtendimento;
		this.idModelo = idModelo;
		this.formularioItems = formularioItems;
	}

	@Id

	@Column(name = "id_formulario", unique = true, nullable = false)
	public long getIdFormulario() {
		return this.idFormulario;
	}

	public void setIdFormulario(long idFormulario) {
		this.idFormulario = idFormulario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_orientacao")
	public FormularioOrientacao getFormularioOrientacao() {
		return this.formularioOrientacao;
	}

	public void setFormularioOrientacao(FormularioOrientacao formularioOrientacao) {
		this.formularioOrientacao = formularioOrientacao;
	}

	@Column(name = "id_usuaria")
	public Long getIdUsuaria() {
		return this.idUsuaria;
	}

	public void setIdUsuaria(Long idUsuaria) {
		this.idUsuaria = idUsuaria;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_inclusao", length = 29)
	public Date getDataInclusao() {
		return this.dataInclusao;
	}

	public void setDataInclusao(Date dataInclusao) {
		this.dataInclusao = dataInclusao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_alteracao", length = 29)
	public Date getDataAlteracao() {
		return this.dataAlteracao;
	}

	public void setDataAlteracao(Date dataAlteracao) {
		this.dataAlteracao = dataAlteracao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_exclusao", length = 29)
	public Date getDataExclusao() {
		return this.dataExclusao;
	}

	public void setDataExclusao(Date dataExclusao) {
		this.dataExclusao = dataExclusao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_conclusao", length = 29)
	public Date getDataConclusao() {
		return this.dataConclusao;
	}

	public void setDataConclusao(Date dataConclusao) {
		this.dataConclusao = dataConclusao;
	}

	@Column(name = "id_tecnico_inclusao")
	public Long getIdTecnicoInclusao() {
		return this.idTecnicoInclusao;
	}

	public void setIdTecnicoInclusao(Long idTecnicoInclusao) {
		this.idTecnicoInclusao = idTecnicoInclusao;
	}

	@Column(name = "id_tecnico_alteracao")
	public Long getIdTecnicoAlteracao() {
		return this.idTecnicoAlteracao;
	}

	public void setIdTecnicoAlteracao(Long idTecnicoAlteracao) {
		this.idTecnicoAlteracao = idTecnicoAlteracao;
	}

	@Column(name = "id_tecnico_exclusao")
	public Long getIdTecnicoExclusao() {
		return this.idTecnicoExclusao;
	}

	public void setIdTecnicoExclusao(Long idTecnicoExclusao) {
		this.idTecnicoExclusao = idTecnicoExclusao;
	}

	@Column(name = "id_tecnico_conclusao")
	public Long getIdTecnicoConclusao() {
		return this.idTecnicoConclusao;
	}

	public void setIdTecnicoConclusao(Long idTecnicoConclusao) {
		this.idTecnicoConclusao = idTecnicoConclusao;
	}

	@Column(name = "id_atendimento", nullable = false)
	public long getIdAtendimento() {
		return this.idAtendimento;
	}

	public void setIdAtendimento(long idAtendimento) {
		this.idAtendimento = idAtendimento;
	}

	@Column(name = "id_modelo")
	public Long getIdModelo() {
		return this.idModelo;
	}

	public void setIdModelo(Long idModelo) {
		this.idModelo = idModelo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formularioCapa")
	public Set getFormularioItems() {
		return this.formularioItems;
	}

	public void setFormularioItems(Set formularioItems) {
		this.formularioItems = formularioItems;
	}

}
