package br.gov.pa.prodepa;
// Generated Nov 1, 2019 4:29:22 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FormularioQuestaoSubResposta generated by hbm2java
 */
@Entity
@Table(name = "formulario_questao_sub_resposta")
public class FormularioQuestaoSubResposta implements java.io.Serializable {

	private long idQuestaoSubResposta;
	private FormularioQuestao formularioQuestao;
	private FormularioResposta formularioResposta;

	public FormularioQuestaoSubResposta() {
	}

	public FormularioQuestaoSubResposta(long idQuestaoSubResposta) {
		this.idQuestaoSubResposta = idQuestaoSubResposta;
	}

	public FormularioQuestaoSubResposta(long idQuestaoSubResposta, FormularioQuestao formularioQuestao,
			FormularioResposta formularioResposta) {
		this.idQuestaoSubResposta = idQuestaoSubResposta;
		this.formularioQuestao = formularioQuestao;
		this.formularioResposta = formularioResposta;
	}

	@Id

	@Column(name = "id_questao_sub_resposta", unique = true, nullable = false)
	public long getIdQuestaoSubResposta() {
		return this.idQuestaoSubResposta;
	}

	public void setIdQuestaoSubResposta(long idQuestaoSubResposta) {
		this.idQuestaoSubResposta = idQuestaoSubResposta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_questao")
	public FormularioQuestao getFormularioQuestao() {
		return this.formularioQuestao;
	}

	public void setFormularioQuestao(FormularioQuestao formularioQuestao) {
		this.formularioQuestao = formularioQuestao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_sub_resposta")
	public FormularioResposta getFormularioResposta() {
		return this.formularioResposta;
	}

	public void setFormularioResposta(FormularioResposta formularioResposta) {
		this.formularioResposta = formularioResposta;
	}

}
