package br.gov.pa.prodepa;
// Generated Nov 1, 2019 4:29:22 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FormularioOrientacao generated by hbm2java
 */
@Entity
@Table(name = "formulario_orientacao")
public class FormularioOrientacao implements java.io.Serializable {

	private long idOrientacao;
	private String dscOrientacao;
	private Date dataInclusao;
	private Date dataAlteracao;
	private Date dataExclusao;
	private Long idTecnicoInclusao;
	private Long idTecnicoAlteracao;
	private Long idTecnicoExclusao;
	private Set formularioCapas = new HashSet(0);

	public FormularioOrientacao() {
	}

	public FormularioOrientacao(long idOrientacao) {
		this.idOrientacao = idOrientacao;
	}

	public FormularioOrientacao(long idOrientacao, String dscOrientacao, Date dataInclusao, Date dataAlteracao,
			Date dataExclusao, Long idTecnicoInclusao, Long idTecnicoAlteracao, Long idTecnicoExclusao,
			Set formularioCapas) {
		this.idOrientacao = idOrientacao;
		this.dscOrientacao = dscOrientacao;
		this.dataInclusao = dataInclusao;
		this.dataAlteracao = dataAlteracao;
		this.dataExclusao = dataExclusao;
		this.idTecnicoInclusao = idTecnicoInclusao;
		this.idTecnicoAlteracao = idTecnicoAlteracao;
		this.idTecnicoExclusao = idTecnicoExclusao;
		this.formularioCapas = formularioCapas;
	}

	@Id

	@Column(name = "id_orientacao", unique = true, nullable = false)
	public long getIdOrientacao() {
		return this.idOrientacao;
	}

	public void setIdOrientacao(long idOrientacao) {
		this.idOrientacao = idOrientacao;
	}

	@Column(name = "dsc_orientacao")
	public String getDscOrientacao() {
		return this.dscOrientacao;
	}

	public void setDscOrientacao(String dscOrientacao) {
		this.dscOrientacao = dscOrientacao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_inclusao", length = 29)
	public Date getDataInclusao() {
		return this.dataInclusao;
	}

	public void setDataInclusao(Date dataInclusao) {
		this.dataInclusao = dataInclusao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_alteracao", length = 29)
	public Date getDataAlteracao() {
		return this.dataAlteracao;
	}

	public void setDataAlteracao(Date dataAlteracao) {
		this.dataAlteracao = dataAlteracao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_exclusao", length = 29)
	public Date getDataExclusao() {
		return this.dataExclusao;
	}

	public void setDataExclusao(Date dataExclusao) {
		this.dataExclusao = dataExclusao;
	}

	@Column(name = "id_tecnico_inclusao")
	public Long getIdTecnicoInclusao() {
		return this.idTecnicoInclusao;
	}

	public void setIdTecnicoInclusao(Long idTecnicoInclusao) {
		this.idTecnicoInclusao = idTecnicoInclusao;
	}

	@Column(name = "id_tecnico_alteracao")
	public Long getIdTecnicoAlteracao() {
		return this.idTecnicoAlteracao;
	}

	public void setIdTecnicoAlteracao(Long idTecnicoAlteracao) {
		this.idTecnicoAlteracao = idTecnicoAlteracao;
	}

	@Column(name = "id_tecnico_exclusao")
	public Long getIdTecnicoExclusao() {
		return this.idTecnicoExclusao;
	}

	public void setIdTecnicoExclusao(Long idTecnicoExclusao) {
		this.idTecnicoExclusao = idTecnicoExclusao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formularioOrientacao")
	public Set getFormularioCapas() {
		return this.formularioCapas;
	}

	public void setFormularioCapas(Set formularioCapas) {
		this.formularioCapas = formularioCapas;
	}

}
