package br.gov.pa.prodepa;
// Generated Nov 1, 2019 4:29:22 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FormularioTipoResposta generated by hbm2java
 */
@Entity
@Table(name = "formulario_tipo_resposta")
public class FormularioTipoResposta implements java.io.Serializable {

	private long idTipoResposta;
	private String dscTipoResposta;
	private Date dataInclusao;
	private Date dataAlteracao;
	private Date dataExclusao;
	private Long idTecnicoInclusao;
	private Long idTecnicoAlteracao;
	private Long idTecnicoExclusao;
	private Set formularioRespostas = new HashSet(0);

	public FormularioTipoResposta() {
	}

	public FormularioTipoResposta(long idTipoResposta) {
		this.idTipoResposta = idTipoResposta;
	}

	public FormularioTipoResposta(long idTipoResposta, String dscTipoResposta, Date dataInclusao, Date dataAlteracao,
			Date dataExclusao, Long idTecnicoInclusao, Long idTecnicoAlteracao, Long idTecnicoExclusao,
			Set formularioRespostas) {
		this.idTipoResposta = idTipoResposta;
		this.dscTipoResposta = dscTipoResposta;
		this.dataInclusao = dataInclusao;
		this.dataAlteracao = dataAlteracao;
		this.dataExclusao = dataExclusao;
		this.idTecnicoInclusao = idTecnicoInclusao;
		this.idTecnicoAlteracao = idTecnicoAlteracao;
		this.idTecnicoExclusao = idTecnicoExclusao;
		this.formularioRespostas = formularioRespostas;
	}

	@Id

	@Column(name = "id_tipo_resposta", unique = true, nullable = false)
	public long getIdTipoResposta() {
		return this.idTipoResposta;
	}

	public void setIdTipoResposta(long idTipoResposta) {
		this.idTipoResposta = idTipoResposta;
	}

	@Column(name = "dsc_tipo_resposta")
	public String getDscTipoResposta() {
		return this.dscTipoResposta;
	}

	public void setDscTipoResposta(String dscTipoResposta) {
		this.dscTipoResposta = dscTipoResposta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_inclusao", length = 29)
	public Date getDataInclusao() {
		return this.dataInclusao;
	}

	public void setDataInclusao(Date dataInclusao) {
		this.dataInclusao = dataInclusao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_alteracao", length = 29)
	public Date getDataAlteracao() {
		return this.dataAlteracao;
	}

	public void setDataAlteracao(Date dataAlteracao) {
		this.dataAlteracao = dataAlteracao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_exclusao", length = 29)
	public Date getDataExclusao() {
		return this.dataExclusao;
	}

	public void setDataExclusao(Date dataExclusao) {
		this.dataExclusao = dataExclusao;
	}

	@Column(name = "id_tecnico_inclusao")
	public Long getIdTecnicoInclusao() {
		return this.idTecnicoInclusao;
	}

	public void setIdTecnicoInclusao(Long idTecnicoInclusao) {
		this.idTecnicoInclusao = idTecnicoInclusao;
	}

	@Column(name = "id_tecnico_alteracao")
	public Long getIdTecnicoAlteracao() {
		return this.idTecnicoAlteracao;
	}

	public void setIdTecnicoAlteracao(Long idTecnicoAlteracao) {
		this.idTecnicoAlteracao = idTecnicoAlteracao;
	}

	@Column(name = "id_tecnico_exclusao")
	public Long getIdTecnicoExclusao() {
		return this.idTecnicoExclusao;
	}

	public void setIdTecnicoExclusao(Long idTecnicoExclusao) {
		this.idTecnicoExclusao = idTecnicoExclusao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formularioTipoResposta")
	public Set getFormularioRespostas() {
		return this.formularioRespostas;
	}

	public void setFormularioRespostas(Set formularioRespostas) {
		this.formularioRespostas = formularioRespostas;
	}

}
