package br.gov.pa.prodepa;
// Generated Nov 1, 2019 4:29:22 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FormularioResposta generated by hbm2java
 */
@Entity
@Table(name = "formulario_resposta")
public class FormularioResposta implements java.io.Serializable {

	private long idResposta;
	private FormularioTipoResposta formularioTipoResposta;
	private String dscResposta;
	private Date dataInclusao;
	private Date dataAlteracao;
	private Date dataExclusao;
	private Long idTecnicoInclusao;
	private Long idTecnicoAlteracao;
	private Long idTecnicoExclusao;
	private Set formularioItems = new HashSet(0);
	private Set formularioQuestaoSubRespostas = new HashSet(0);
	private Set formularioQuestaoRespostas = new HashSet(0);

	public FormularioResposta() {
	}

	public FormularioResposta(long idResposta) {
		this.idResposta = idResposta;
	}

	public FormularioResposta(long idResposta, FormularioTipoResposta formularioTipoResposta, String dscResposta,
			Date dataInclusao, Date dataAlteracao, Date dataExclusao, Long idTecnicoInclusao, Long idTecnicoAlteracao,
			Long idTecnicoExclusao, Set formularioItems, Set formularioQuestaoSubRespostas,
			Set formularioQuestaoRespostas) {
		this.idResposta = idResposta;
		this.formularioTipoResposta = formularioTipoResposta;
		this.dscResposta = dscResposta;
		this.dataInclusao = dataInclusao;
		this.dataAlteracao = dataAlteracao;
		this.dataExclusao = dataExclusao;
		this.idTecnicoInclusao = idTecnicoInclusao;
		this.idTecnicoAlteracao = idTecnicoAlteracao;
		this.idTecnicoExclusao = idTecnicoExclusao;
		this.formularioItems = formularioItems;
		this.formularioQuestaoSubRespostas = formularioQuestaoSubRespostas;
		this.formularioQuestaoRespostas = formularioQuestaoRespostas;
	}

	@Id

	@Column(name = "id_resposta", unique = true, nullable = false)
	public long getIdResposta() {
		return this.idResposta;
	}

	public void setIdResposta(long idResposta) {
		this.idResposta = idResposta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_resposta")
	public FormularioTipoResposta getFormularioTipoResposta() {
		return this.formularioTipoResposta;
	}

	public void setFormularioTipoResposta(FormularioTipoResposta formularioTipoResposta) {
		this.formularioTipoResposta = formularioTipoResposta;
	}

	@Column(name = "dsc_resposta")
	public String getDscResposta() {
		return this.dscResposta;
	}

	public void setDscResposta(String dscResposta) {
		this.dscResposta = dscResposta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_inclusao", length = 29)
	public Date getDataInclusao() {
		return this.dataInclusao;
	}

	public void setDataInclusao(Date dataInclusao) {
		this.dataInclusao = dataInclusao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_alteracao", length = 29)
	public Date getDataAlteracao() {
		return this.dataAlteracao;
	}

	public void setDataAlteracao(Date dataAlteracao) {
		this.dataAlteracao = dataAlteracao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_exclusao", length = 29)
	public Date getDataExclusao() {
		return this.dataExclusao;
	}

	public void setDataExclusao(Date dataExclusao) {
		this.dataExclusao = dataExclusao;
	}

	@Column(name = "id_tecnico_inclusao")
	public Long getIdTecnicoInclusao() {
		return this.idTecnicoInclusao;
	}

	public void setIdTecnicoInclusao(Long idTecnicoInclusao) {
		this.idTecnicoInclusao = idTecnicoInclusao;
	}

	@Column(name = "id_tecnico_alteracao")
	public Long getIdTecnicoAlteracao() {
		return this.idTecnicoAlteracao;
	}

	public void setIdTecnicoAlteracao(Long idTecnicoAlteracao) {
		this.idTecnicoAlteracao = idTecnicoAlteracao;
	}

	@Column(name = "id_tecnico_exclusao")
	public Long getIdTecnicoExclusao() {
		return this.idTecnicoExclusao;
	}

	public void setIdTecnicoExclusao(Long idTecnicoExclusao) {
		this.idTecnicoExclusao = idTecnicoExclusao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formularioResposta")
	public Set getFormularioItems() {
		return this.formularioItems;
	}

	public void setFormularioItems(Set formularioItems) {
		this.formularioItems = formularioItems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formularioResposta")
	public Set getFormularioQuestaoSubRespostas() {
		return this.formularioQuestaoSubRespostas;
	}

	public void setFormularioQuestaoSubRespostas(Set formularioQuestaoSubRespostas) {
		this.formularioQuestaoSubRespostas = formularioQuestaoSubRespostas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formularioResposta")
	public Set getFormularioQuestaoRespostas() {
		return this.formularioQuestaoRespostas;
	}

	public void setFormularioQuestaoRespostas(Set formularioQuestaoRespostas) {
		this.formularioQuestaoRespostas = formularioQuestaoRespostas;
	}

}
