package br.gov.pa.prodepa;
// Generated Nov 1, 2019 4:29:22 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FormularioQuestao generated by hbm2java
 */
@Entity
@Table(name = "formulario_questao")
public class FormularioQuestao implements java.io.Serializable {

	private long idQuestao;
	private FormularioModelo formularioModelo;
	private String idOrdem;
	private String dscQuestao;
	private Boolean flgComplemento;
	private Date dataInclusao;
	private Date dataAlteracao;
	private Date dataExclusao;
	private Long idTecnicoInclusao;
	private Long idTecnicoAlteracao;
	private Long idTecnicoExclusao;
	private Set formularioQuestaoRespostas = new HashSet(0);
	private Set formularioItems = new HashSet(0);
	private Set formularioQuestaoSubRespostas = new HashSet(0);

	public FormularioQuestao() {
	}

	public FormularioQuestao(long idQuestao) {
		this.idQuestao = idQuestao;
	}

	public FormularioQuestao(long idQuestao, FormularioModelo formularioModelo, String idOrdem, String dscQuestao,
			Boolean flgComplemento, Date dataInclusao, Date dataAlteracao, Date dataExclusao, Long idTecnicoInclusao,
			Long idTecnicoAlteracao, Long idTecnicoExclusao, Set formularioQuestaoRespostas, Set formularioItems,
			Set formularioQuestaoSubRespostas) {
		this.idQuestao = idQuestao;
		this.formularioModelo = formularioModelo;
		this.idOrdem = idOrdem;
		this.dscQuestao = dscQuestao;
		this.flgComplemento = flgComplemento;
		this.dataInclusao = dataInclusao;
		this.dataAlteracao = dataAlteracao;
		this.dataExclusao = dataExclusao;
		this.idTecnicoInclusao = idTecnicoInclusao;
		this.idTecnicoAlteracao = idTecnicoAlteracao;
		this.idTecnicoExclusao = idTecnicoExclusao;
		this.formularioQuestaoRespostas = formularioQuestaoRespostas;
		this.formularioItems = formularioItems;
		this.formularioQuestaoSubRespostas = formularioQuestaoSubRespostas;
	}

	@Id

	@Column(name = "id_questao", unique = true, nullable = false)
	public long getIdQuestao() {
		return this.idQuestao;
	}

	public void setIdQuestao(long idQuestao) {
		this.idQuestao = idQuestao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_modelo")
	public FormularioModelo getFormularioModelo() {
		return this.formularioModelo;
	}

	public void setFormularioModelo(FormularioModelo formularioModelo) {
		this.formularioModelo = formularioModelo;
	}

	@Column(name = "id_ordem", length = 10)
	public String getIdOrdem() {
		return this.idOrdem;
	}

	public void setIdOrdem(String idOrdem) {
		this.idOrdem = idOrdem;
	}

	@Column(name = "dsc_questao")
	public String getDscQuestao() {
		return this.dscQuestao;
	}

	public void setDscQuestao(String dscQuestao) {
		this.dscQuestao = dscQuestao;
	}

	@Column(name = "flg_complemento")
	public Boolean getFlgComplemento() {
		return this.flgComplemento;
	}

	public void setFlgComplemento(Boolean flgComplemento) {
		this.flgComplemento = flgComplemento;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_inclusao", length = 29)
	public Date getDataInclusao() {
		return this.dataInclusao;
	}

	public void setDataInclusao(Date dataInclusao) {
		this.dataInclusao = dataInclusao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_alteracao", length = 29)
	public Date getDataAlteracao() {
		return this.dataAlteracao;
	}

	public void setDataAlteracao(Date dataAlteracao) {
		this.dataAlteracao = dataAlteracao;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data_exclusao", length = 13)
	public Date getDataExclusao() {
		return this.dataExclusao;
	}

	public void setDataExclusao(Date dataExclusao) {
		this.dataExclusao = dataExclusao;
	}

	@Column(name = "id_tecnico_inclusao")
	public Long getIdTecnicoInclusao() {
		return this.idTecnicoInclusao;
	}

	public void setIdTecnicoInclusao(Long idTecnicoInclusao) {
		this.idTecnicoInclusao = idTecnicoInclusao;
	}

	@Column(name = "id_tecnico_alteracao")
	public Long getIdTecnicoAlteracao() {
		return this.idTecnicoAlteracao;
	}

	public void setIdTecnicoAlteracao(Long idTecnicoAlteracao) {
		this.idTecnicoAlteracao = idTecnicoAlteracao;
	}

	@Column(name = "id_tecnico_exclusao")
	public Long getIdTecnicoExclusao() {
		return this.idTecnicoExclusao;
	}

	public void setIdTecnicoExclusao(Long idTecnicoExclusao) {
		this.idTecnicoExclusao = idTecnicoExclusao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formularioQuestao")
	public Set getFormularioQuestaoRespostas() {
		return this.formularioQuestaoRespostas;
	}

	public void setFormularioQuestaoRespostas(Set formularioQuestaoRespostas) {
		this.formularioQuestaoRespostas = formularioQuestaoRespostas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formularioQuestao")
	public Set getFormularioItems() {
		return this.formularioItems;
	}

	public void setFormularioItems(Set formularioItems) {
		this.formularioItems = formularioItems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formularioQuestao")
	public Set getFormularioQuestaoSubRespostas() {
		return this.formularioQuestaoSubRespostas;
	}

	public void setFormularioQuestaoSubRespostas(Set formularioQuestaoSubRespostas) {
		this.formularioQuestaoSubRespostas = formularioQuestaoSubRespostas;
	}

}
