package br.gov.pa.prodepa;
// Generated Nov 1, 2019 4:29:22 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FormularioItem generated by hbm2java
 */
@Entity
@Table(name = "formulario_item")
public class FormularioItem implements java.io.Serializable {

	private long idFormularioItem;
	private FormularioCapa formularioCapa;
	private FormularioQuestao formularioQuestao;
	private FormularioResposta formularioResposta;
	private Boolean flgComplemento;
	private Boolean indResposta;
	private String dscQuestao;
	private String dscResposta;
	private String dscComplemento;
	private Date dataInclusao;
	private Date dataAlteracao;
	private Date dataExclusao;
	private Long idTecnicoInclusao;
	private Long idTecnicoAlteracao;
	private Long idTecnicoExclusao;
	private Long idSubResposta;
	private String dscSubResposta;

	public FormularioItem() {
	}

	public FormularioItem(long idFormularioItem) {
		this.idFormularioItem = idFormularioItem;
	}

	public FormularioItem(long idFormularioItem, FormularioCapa formularioCapa, FormularioQuestao formularioQuestao,
			FormularioResposta formularioResposta, Boolean flgComplemento, Boolean indResposta, String dscQuestao,
			String dscResposta, String dscComplemento, Date dataInclusao, Date dataAlteracao, Date dataExclusao,
			Long idTecnicoInclusao, Long idTecnicoAlteracao, Long idTecnicoExclusao, Long idSubResposta,
			String dscSubResposta) {
		this.idFormularioItem = idFormularioItem;
		this.formularioCapa = formularioCapa;
		this.formularioQuestao = formularioQuestao;
		this.formularioResposta = formularioResposta;
		this.flgComplemento = flgComplemento;
		this.indResposta = indResposta;
		this.dscQuestao = dscQuestao;
		this.dscResposta = dscResposta;
		this.dscComplemento = dscComplemento;
		this.dataInclusao = dataInclusao;
		this.dataAlteracao = dataAlteracao;
		this.dataExclusao = dataExclusao;
		this.idTecnicoInclusao = idTecnicoInclusao;
		this.idTecnicoAlteracao = idTecnicoAlteracao;
		this.idTecnicoExclusao = idTecnicoExclusao;
		this.idSubResposta = idSubResposta;
		this.dscSubResposta = dscSubResposta;
	}

	@Id

	@Column(name = "id_formulario_item", unique = true, nullable = false)
	public long getIdFormularioItem() {
		return this.idFormularioItem;
	}

	public void setIdFormularioItem(long idFormularioItem) {
		this.idFormularioItem = idFormularioItem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_formulario")
	public FormularioCapa getFormularioCapa() {
		return this.formularioCapa;
	}

	public void setFormularioCapa(FormularioCapa formularioCapa) {
		this.formularioCapa = formularioCapa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_questao")
	public FormularioQuestao getFormularioQuestao() {
		return this.formularioQuestao;
	}

	public void setFormularioQuestao(FormularioQuestao formularioQuestao) {
		this.formularioQuestao = formularioQuestao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_resposta")
	public FormularioResposta getFormularioResposta() {
		return this.formularioResposta;
	}

	public void setFormularioResposta(FormularioResposta formularioResposta) {
		this.formularioResposta = formularioResposta;
	}

	@Column(name = "flg_complemento")
	public Boolean getFlgComplemento() {
		return this.flgComplemento;
	}

	public void setFlgComplemento(Boolean flgComplemento) {
		this.flgComplemento = flgComplemento;
	}

	@Column(name = "ind_resposta")
	public Boolean getIndResposta() {
		return this.indResposta;
	}

	public void setIndResposta(Boolean indResposta) {
		this.indResposta = indResposta;
	}

	@Column(name = "dsc_questao")
	public String getDscQuestao() {
		return this.dscQuestao;
	}

	public void setDscQuestao(String dscQuestao) {
		this.dscQuestao = dscQuestao;
	}

	@Column(name = "dsc_resposta")
	public String getDscResposta() {
		return this.dscResposta;
	}

	public void setDscResposta(String dscResposta) {
		this.dscResposta = dscResposta;
	}

	@Column(name = "dsc_complemento")
	public String getDscComplemento() {
		return this.dscComplemento;
	}

	public void setDscComplemento(String dscComplemento) {
		this.dscComplemento = dscComplemento;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_inclusao", length = 29)
	public Date getDataInclusao() {
		return this.dataInclusao;
	}

	public void setDataInclusao(Date dataInclusao) {
		this.dataInclusao = dataInclusao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_alteracao", length = 29)
	public Date getDataAlteracao() {
		return this.dataAlteracao;
	}

	public void setDataAlteracao(Date dataAlteracao) {
		this.dataAlteracao = dataAlteracao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_exclusao", length = 29)
	public Date getDataExclusao() {
		return this.dataExclusao;
	}

	public void setDataExclusao(Date dataExclusao) {
		this.dataExclusao = dataExclusao;
	}

	@Column(name = "id_tecnico_inclusao")
	public Long getIdTecnicoInclusao() {
		return this.idTecnicoInclusao;
	}

	public void setIdTecnicoInclusao(Long idTecnicoInclusao) {
		this.idTecnicoInclusao = idTecnicoInclusao;
	}

	@Column(name = "id_tecnico_alteracao")
	public Long getIdTecnicoAlteracao() {
		return this.idTecnicoAlteracao;
	}

	public void setIdTecnicoAlteracao(Long idTecnicoAlteracao) {
		this.idTecnicoAlteracao = idTecnicoAlteracao;
	}

	@Column(name = "id_tecnico_exclusao")
	public Long getIdTecnicoExclusao() {
		return this.idTecnicoExclusao;
	}

	public void setIdTecnicoExclusao(Long idTecnicoExclusao) {
		this.idTecnicoExclusao = idTecnicoExclusao;
	}

	@Column(name = "id_sub_resposta")
	public Long getIdSubResposta() {
		return this.idSubResposta;
	}

	public void setIdSubResposta(Long idSubResposta) {
		this.idSubResposta = idSubResposta;
	}

	@Column(name = "dsc_sub_resposta")
	public String getDscSubResposta() {
		return this.dscSubResposta;
	}

	public void setDscSubResposta(String dscSubResposta) {
		this.dscSubResposta = dscSubResposta;
	}

}
