package br.gov.pa.prodepa;
// Generated Nov 1, 2019 4:29:22 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FridaSubresposta generated by hbm2java
 */
@Entity
@Table(name = "frida_subresposta")
public class FridaSubresposta implements java.io.Serializable {

	private int id;
	private FridaPerguntas fridaPerguntas;
	private String descricao;
	private Set atendimentoFridaRespotases = new HashSet(0);

	public FridaSubresposta() {
	}

	public FridaSubresposta(int id) {
		this.id = id;
	}

	public FridaSubresposta(int id, FridaPerguntas fridaPerguntas, String descricao, Set atendimentoFridaRespotases) {
		this.id = id;
		this.fridaPerguntas = fridaPerguntas;
		this.descricao = descricao;
		this.atendimentoFridaRespotases = atendimentoFridaRespotases;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_pergunta")
	public FridaPerguntas getFridaPerguntas() {
		return this.fridaPerguntas;
	}

	public void setFridaPerguntas(FridaPerguntas fridaPerguntas) {
		this.fridaPerguntas = fridaPerguntas;
	}

	@Column(name = "descricao", length = 25)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fridaSubresposta")
	public Set getAtendimentoFridaRespotases() {
		return this.atendimentoFridaRespotases;
	}

	public void setAtendimentoFridaRespotases(Set atendimentoFridaRespotases) {
		this.atendimentoFridaRespotases = atendimentoFridaRespotases;
	}

}
