package br.gov.pa.prodepa;
// Generated Nov 1, 2019 4:29:22 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * GrauRelacao generated by hbm2java
 */
@Entity
@Table(name = "grau_relacao", uniqueConstraints = @UniqueConstraint(columnNames = "descricao"))
public class GrauRelacao implements java.io.Serializable {

	private long id;
	private String descricao;
	private int situacao;
	private Set residentes = new HashSet(0);
	private Set dependentesForComQuemMora = new HashSet(0);
	private Set atendimentoAgressors = new HashSet(0);
	private Set dependentesForIdGrauRelacao = new HashSet(0);
	private Set usuariaViolencias = new HashSet(0);
	private Set enderecos = new HashSet(0);

	public GrauRelacao() {
	}

	public GrauRelacao(long id, String descricao, int situacao) {
		this.id = id;
		this.descricao = descricao;
		this.situacao = situacao;
	}

	public GrauRelacao(long id, String descricao, int situacao, Set residentes, Set dependentesForComQuemMora,
			Set atendimentoAgressors, Set dependentesForIdGrauRelacao, Set usuariaViolencias, Set enderecos) {
		this.id = id;
		this.descricao = descricao;
		this.situacao = situacao;
		this.residentes = residentes;
		this.dependentesForComQuemMora = dependentesForComQuemMora;
		this.atendimentoAgressors = atendimentoAgressors;
		this.dependentesForIdGrauRelacao = dependentesForIdGrauRelacao;
		this.usuariaViolencias = usuariaViolencias;
		this.enderecos = enderecos;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "descricao", unique = true, nullable = false)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "situacao", nullable = false)
	public int getSituacao() {
		return this.situacao;
	}

	public void setSituacao(int situacao) {
		this.situacao = situacao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grauRelacao")
	public Set getResidentes() {
		return this.residentes;
	}

	public void setResidentes(Set residentes) {
		this.residentes = residentes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grauRelacaoByComQuemMora")
	public Set getDependentesForComQuemMora() {
		return this.dependentesForComQuemMora;
	}

	public void setDependentesForComQuemMora(Set dependentesForComQuemMora) {
		this.dependentesForComQuemMora = dependentesForComQuemMora;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grauRelacao")
	public Set getAtendimentoAgressors() {
		return this.atendimentoAgressors;
	}

	public void setAtendimentoAgressors(Set atendimentoAgressors) {
		this.atendimentoAgressors = atendimentoAgressors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grauRelacaoByIdGrauRelacao")
	public Set getDependentesForIdGrauRelacao() {
		return this.dependentesForIdGrauRelacao;
	}

	public void setDependentesForIdGrauRelacao(Set dependentesForIdGrauRelacao) {
		this.dependentesForIdGrauRelacao = dependentesForIdGrauRelacao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grauRelacao")
	public Set getUsuariaViolencias() {
		return this.usuariaViolencias;
	}

	public void setUsuariaViolencias(Set usuariaViolencias) {
		this.usuariaViolencias = usuariaViolencias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grauRelacao")
	public Set getEnderecos() {
		return this.enderecos;
	}

	public void setEnderecos(Set enderecos) {
		this.enderecos = enderecos;
	}

}
