package br.gov.pa.prodepa;
// Generated Nov 1, 2019 4:29:22 PM by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HistoricoAgressor generated by hbm2java
 */
@Entity
@Table(name = "historico_agressor")
public class HistoricoAgressor implements java.io.Serializable {

	private long id;
	private Long idAtendimento;
	private long idAgressor;
	private String nome;
	private Date dataNascimento;
	private BigDecimal valorRenda;
	private Integer possuiAntecedente;
	private String listaQuaisAntecedentes;
	private Integer violentoComFamilia;
	private String descricaoViolentoComFamilia;
	private Integer fazUsoDroga;
	private Integer fazUsoMedicacao;
	private Integer fazUsoAlcool;
	private Integer frequenciaUsoAlcool;
	private Integer nivelEscolaridade;
	private String listaAgressorEntorpecente;
	private String listaAgressorTipoMedicacao;
	private String ocupacao;
	private String profissao;
	private Integer situacao;
	private Date dataHoraCadastro;
	private Long usuario;
	private Long idEvolucaoAtendimento;

	public HistoricoAgressor() {
	}

	public HistoricoAgressor(long id, long idAgressor) {
		this.id = id;
		this.idAgressor = idAgressor;
	}

	public HistoricoAgressor(long id, Long idAtendimento, long idAgressor, String nome, Date dataNascimento,
			BigDecimal valorRenda, Integer possuiAntecedente, String listaQuaisAntecedentes, Integer violentoComFamilia,
			String descricaoViolentoComFamilia, Integer fazUsoDroga, Integer fazUsoMedicacao, Integer fazUsoAlcool,
			Integer frequenciaUsoAlcool, Integer nivelEscolaridade, String listaAgressorEntorpecente,
			String listaAgressorTipoMedicacao, String ocupacao, String profissao, Integer situacao,
			Date dataHoraCadastro, Long usuario, Long idEvolucaoAtendimento) {
		this.id = id;
		this.idAtendimento = idAtendimento;
		this.idAgressor = idAgressor;
		this.nome = nome;
		this.dataNascimento = dataNascimento;
		this.valorRenda = valorRenda;
		this.possuiAntecedente = possuiAntecedente;
		this.listaQuaisAntecedentes = listaQuaisAntecedentes;
		this.violentoComFamilia = violentoComFamilia;
		this.descricaoViolentoComFamilia = descricaoViolentoComFamilia;
		this.fazUsoDroga = fazUsoDroga;
		this.fazUsoMedicacao = fazUsoMedicacao;
		this.fazUsoAlcool = fazUsoAlcool;
		this.frequenciaUsoAlcool = frequenciaUsoAlcool;
		this.nivelEscolaridade = nivelEscolaridade;
		this.listaAgressorEntorpecente = listaAgressorEntorpecente;
		this.listaAgressorTipoMedicacao = listaAgressorTipoMedicacao;
		this.ocupacao = ocupacao;
		this.profissao = profissao;
		this.situacao = situacao;
		this.dataHoraCadastro = dataHoraCadastro;
		this.usuario = usuario;
		this.idEvolucaoAtendimento = idEvolucaoAtendimento;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "id_atendimento")
	public Long getIdAtendimento() {
		return this.idAtendimento;
	}

	public void setIdAtendimento(Long idAtendimento) {
		this.idAtendimento = idAtendimento;
	}

	@Column(name = "id_agressor", nullable = false)
	public long getIdAgressor() {
		return this.idAgressor;
	}

	public void setIdAgressor(long idAgressor) {
		this.idAgressor = idAgressor;
	}

	@Column(name = "nome")
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data_nascimento", length = 13)
	public Date getDataNascimento() {
		return this.dataNascimento;
	}

	public void setDataNascimento(Date dataNascimento) {
		this.dataNascimento = dataNascimento;
	}

	@Column(name = "valor_renda", precision = 9)
	public BigDecimal getValorRenda() {
		return this.valorRenda;
	}

	public void setValorRenda(BigDecimal valorRenda) {
		this.valorRenda = valorRenda;
	}

	@Column(name = "possui_antecedente")
	public Integer getPossuiAntecedente() {
		return this.possuiAntecedente;
	}

	public void setPossuiAntecedente(Integer possuiAntecedente) {
		this.possuiAntecedente = possuiAntecedente;
	}

	@Column(name = "lista_quais_antecedentes")
	public String getListaQuaisAntecedentes() {
		return this.listaQuaisAntecedentes;
	}

	public void setListaQuaisAntecedentes(String listaQuaisAntecedentes) {
		this.listaQuaisAntecedentes = listaQuaisAntecedentes;
	}

	@Column(name = "violento_com_familia")
	public Integer getViolentoComFamilia() {
		return this.violentoComFamilia;
	}

	public void setViolentoComFamilia(Integer violentoComFamilia) {
		this.violentoComFamilia = violentoComFamilia;
	}

	@Column(name = "descricao_violento_com_familia")
	public String getDescricaoViolentoComFamilia() {
		return this.descricaoViolentoComFamilia;
	}

	public void setDescricaoViolentoComFamilia(String descricaoViolentoComFamilia) {
		this.descricaoViolentoComFamilia = descricaoViolentoComFamilia;
	}

	@Column(name = "faz_uso_droga")
	public Integer getFazUsoDroga() {
		return this.fazUsoDroga;
	}

	public void setFazUsoDroga(Integer fazUsoDroga) {
		this.fazUsoDroga = fazUsoDroga;
	}

	@Column(name = "faz_uso_medicacao")
	public Integer getFazUsoMedicacao() {
		return this.fazUsoMedicacao;
	}

	public void setFazUsoMedicacao(Integer fazUsoMedicacao) {
		this.fazUsoMedicacao = fazUsoMedicacao;
	}

	@Column(name = "faz_uso_alcool")
	public Integer getFazUsoAlcool() {
		return this.fazUsoAlcool;
	}

	public void setFazUsoAlcool(Integer fazUsoAlcool) {
		this.fazUsoAlcool = fazUsoAlcool;
	}

	@Column(name = "frequencia_uso_alcool")
	public Integer getFrequenciaUsoAlcool() {
		return this.frequenciaUsoAlcool;
	}

	public void setFrequenciaUsoAlcool(Integer frequenciaUsoAlcool) {
		this.frequenciaUsoAlcool = frequenciaUsoAlcool;
	}

	@Column(name = "nivel_escolaridade")
	public Integer getNivelEscolaridade() {
		return this.nivelEscolaridade;
	}

	public void setNivelEscolaridade(Integer nivelEscolaridade) {
		this.nivelEscolaridade = nivelEscolaridade;
	}

	@Column(name = "lista_agressor_entorpecente")
	public String getListaAgressorEntorpecente() {
		return this.listaAgressorEntorpecente;
	}

	public void setListaAgressorEntorpecente(String listaAgressorEntorpecente) {
		this.listaAgressorEntorpecente = listaAgressorEntorpecente;
	}

	@Column(name = "lista_agressor_tipo_medicacao")
	public String getListaAgressorTipoMedicacao() {
		return this.listaAgressorTipoMedicacao;
	}

	public void setListaAgressorTipoMedicacao(String listaAgressorTipoMedicacao) {
		this.listaAgressorTipoMedicacao = listaAgressorTipoMedicacao;
	}

	@Column(name = "ocupacao")
	public String getOcupacao() {
		return this.ocupacao;
	}

	public void setOcupacao(String ocupacao) {
		this.ocupacao = ocupacao;
	}

	@Column(name = "profissao")
	public String getProfissao() {
		return this.profissao;
	}

	public void setProfissao(String profissao) {
		this.profissao = profissao;
	}

	@Column(name = "situacao")
	public Integer getSituacao() {
		return this.situacao;
	}

	public void setSituacao(Integer situacao) {
		this.situacao = situacao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_hora_cadastro", length = 29)
	public Date getDataHoraCadastro() {
		return this.dataHoraCadastro;
	}

	public void setDataHoraCadastro(Date dataHoraCadastro) {
		this.dataHoraCadastro = dataHoraCadastro;
	}

	@Column(name = "usuario")
	public Long getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Long usuario) {
		this.usuario = usuario;
	}

	@Column(name = "id_evolucao_atendimento")
	public Long getIdEvolucaoAtendimento() {
		return this.idEvolucaoAtendimento;
	}

	public void setIdEvolucaoAtendimento(Long idEvolucaoAtendimento) {
		this.idEvolucaoAtendimento = idEvolucaoAtendimento;
	}

}
