package br.gov.pa.prodepa;
// Generated Nov 1, 2019 4:29:22 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Municipio generated by hbm2java
 */
@Entity
@Table(name = "municipio")
public class Municipio implements java.io.Serializable {

	private long idMunicipio;
	private Regiao regiao;
	private Date dataInicio;

	public Municipio() {
	}

	public Municipio(long idMunicipio, Regiao regiao, Date dataInicio) {
		this.idMunicipio = idMunicipio;
		this.regiao = regiao;
		this.dataInicio = dataInicio;
	}

	@Id

	@Column(name = "id_municipio", unique = true, nullable = false)
	public long getIdMunicipio() {
		return this.idMunicipio;
	}

	public void setIdMunicipio(long idMunicipio) {
		this.idMunicipio = idMunicipio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_regiao", nullable = false)
	public Regiao getRegiao() {
		return this.regiao;
	}

	public void setRegiao(Regiao regiao) {
		this.regiao = regiao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_inicio", nullable = false, length = 29)
	public Date getDataInicio() {
		return this.dataInicio;
	}

	public void setDataInicio(Date dataInicio) {
		this.dataInicio = dataInicio;
	}

}
