package br.gov.pa.prodepa;
// Generated Nov 1, 2019 4:29:22 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * ObjetoAgressao generated by hbm2java
 */
@Entity
@Table(name = "objeto_agressao")
public class ObjetoAgressao implements java.io.Serializable {

	private long id;
	private String descricao;
	private int situacao;
	private Set atendimentos = new HashSet(0);

	public ObjetoAgressao() {
	}

	public ObjetoAgressao(long id, String descricao, int situacao) {
		this.id = id;
		this.descricao = descricao;
		this.situacao = situacao;
	}

	public ObjetoAgressao(long id, String descricao, int situacao, Set atendimentos) {
		this.id = id;
		this.descricao = descricao;
		this.situacao = situacao;
		this.atendimentos = atendimentos;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "descricao", nullable = false)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "situacao", nullable = false)
	public int getSituacao() {
		return this.situacao;
	}

	public void setSituacao(int situacao) {
		this.situacao = situacao;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "atendimento_objeto_agressao", joinColumns = {
			@JoinColumn(name = "id_objeto_agressao", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "id_atendimento", nullable = false, updatable = false) })
	public Set getAtendimentos() {
		return this.atendimentos;
	}

	public void setAtendimentos(Set atendimentos) {
		this.atendimentos = atendimentos;
	}

}
