package br.gov.pa.prodepa;
// Generated Nov 1, 2019 4:29:22 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OcupacaoBkp generated by hbm2java
 */
@Entity
@Table(name = "ocupacao_bkp")
public class OcupacaoBkp implements java.io.Serializable {

	private long id;
	private String descricao;
	private int situacao;

	public OcupacaoBkp() {
	}

	public OcupacaoBkp(long id, String descricao, int situacao) {
		this.id = id;
		this.descricao = descricao;
		this.situacao = situacao;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "descricao", nullable = false, length = 100)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "situacao", nullable = false)
	public int getSituacao() {
		return this.situacao;
	}

	public void setSituacao(int situacao) {
		this.situacao = situacao;
	}

}
