package br.gov.pa.prodepa;
// Generated Nov 1, 2019 4:29:22 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Ocupacao generated by hbm2java
 */
@Entity
@Table(name = "ocupacao", uniqueConstraints = @UniqueConstraint(columnNames = { "descricao", "cod_cbo" }))
public class Ocupacao implements java.io.Serializable {

	private long id;
	private String descricao;
	private int situacao;
	private Long codCbo;
	private Set usuariasForIdOcupacaoProfissao = new HashSet(0);
	private Set dependentes = new HashSet(0);
	private Set agressorsForIdOcupacaoProfissao = new HashSet(0);
	private Set agressorsForIdOcupacao = new HashSet(0);
	private Set residentes = new HashSet(0);
	private Set usuariasForIdOcupacao = new HashSet(0);
	private Set tecnicos = new HashSet(0);

	public Ocupacao() {
	}

	public Ocupacao(long id, String descricao, int situacao) {
		this.id = id;
		this.descricao = descricao;
		this.situacao = situacao;
	}

	public Ocupacao(long id, String descricao, int situacao, Long codCbo, Set usuariasForIdOcupacaoProfissao,
			Set dependentes, Set agressorsForIdOcupacaoProfissao, Set agressorsForIdOcupacao, Set residentes,
			Set usuariasForIdOcupacao, Set tecnicos) {
		this.id = id;
		this.descricao = descricao;
		this.situacao = situacao;
		this.codCbo = codCbo;
		this.usuariasForIdOcupacaoProfissao = usuariasForIdOcupacaoProfissao;
		this.dependentes = dependentes;
		this.agressorsForIdOcupacaoProfissao = agressorsForIdOcupacaoProfissao;
		this.agressorsForIdOcupacao = agressorsForIdOcupacao;
		this.residentes = residentes;
		this.usuariasForIdOcupacao = usuariasForIdOcupacao;
		this.tecnicos = tecnicos;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "descricao", nullable = false, length = 200)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "situacao", nullable = false)
	public int getSituacao() {
		return this.situacao;
	}

	public void setSituacao(int situacao) {
		this.situacao = situacao;
	}

	@Column(name = "cod_cbo")
	public Long getCodCbo() {
		return this.codCbo;
	}

	public void setCodCbo(Long codCbo) {
		this.codCbo = codCbo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ocupacaoByIdOcupacaoProfissao")
	public Set getUsuariasForIdOcupacaoProfissao() {
		return this.usuariasForIdOcupacaoProfissao;
	}

	public void setUsuariasForIdOcupacaoProfissao(Set usuariasForIdOcupacaoProfissao) {
		this.usuariasForIdOcupacaoProfissao = usuariasForIdOcupacaoProfissao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ocupacao")
	public Set getDependentes() {
		return this.dependentes;
	}

	public void setDependentes(Set dependentes) {
		this.dependentes = dependentes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ocupacaoByIdOcupacaoProfissao")
	public Set getAgressorsForIdOcupacaoProfissao() {
		return this.agressorsForIdOcupacaoProfissao;
	}

	public void setAgressorsForIdOcupacaoProfissao(Set agressorsForIdOcupacaoProfissao) {
		this.agressorsForIdOcupacaoProfissao = agressorsForIdOcupacaoProfissao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ocupacaoByIdOcupacao")
	public Set getAgressorsForIdOcupacao() {
		return this.agressorsForIdOcupacao;
	}

	public void setAgressorsForIdOcupacao(Set agressorsForIdOcupacao) {
		this.agressorsForIdOcupacao = agressorsForIdOcupacao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ocupacao")
	public Set getResidentes() {
		return this.residentes;
	}

	public void setResidentes(Set residentes) {
		this.residentes = residentes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ocupacaoByIdOcupacao")
	public Set getUsuariasForIdOcupacao() {
		return this.usuariasForIdOcupacao;
	}

	public void setUsuariasForIdOcupacao(Set usuariasForIdOcupacao) {
		this.usuariasForIdOcupacao = usuariasForIdOcupacao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ocupacao")
	public Set getTecnicos() {
		return this.tecnicos;
	}

	public void setTecnicos(Set tecnicos) {
		this.tecnicos = tecnicos;
	}

}
