package br.gov.pa.prodepa;
// Generated Nov 1, 2019 4:29:22 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OrigemEncaminhamento generated by hbm2java
 */
@Entity
@Table(name = "origem_encaminhamento")
public class OrigemEncaminhamento implements java.io.Serializable {

	private long id;
	private String descricao;
	private int situacao;
	private Set preAcolhimentos = new HashSet(0);
	private Set encaminhamentos = new HashSet(0);

	public OrigemEncaminhamento() {
	}

	public OrigemEncaminhamento(long id, String descricao, int situacao) {
		this.id = id;
		this.descricao = descricao;
		this.situacao = situacao;
	}

	public OrigemEncaminhamento(long id, String descricao, int situacao, Set preAcolhimentos, Set encaminhamentos) {
		this.id = id;
		this.descricao = descricao;
		this.situacao = situacao;
		this.preAcolhimentos = preAcolhimentos;
		this.encaminhamentos = encaminhamentos;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "descricao", nullable = false)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "situacao", nullable = false)
	public int getSituacao() {
		return this.situacao;
	}

	public void setSituacao(int situacao) {
		this.situacao = situacao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "origemEncaminhamento")
	public Set getPreAcolhimentos() {
		return this.preAcolhimentos;
	}

	public void setPreAcolhimentos(Set preAcolhimentos) {
		this.preAcolhimentos = preAcolhimentos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "origemEncaminhamento")
	public Set getEncaminhamentos() {
		return this.encaminhamentos;
	}

	public void setEncaminhamentos(Set encaminhamentos) {
		this.encaminhamentos = encaminhamentos;
	}

}
