package br.gov.pa.prodepa;
// Generated Nov 1, 2019 4:29:22 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PreAcolhimento generated by hbm2java
 */
@Entity
@Table(name = "pre_acolhimento")
public class PreAcolhimento implements java.io.Serializable {

	private long id;
	private Centro centro;
	private OrigemEncaminhamento origemEncaminhamento;
	private Tecnico tecnico;
	private Usuaria usuaria;
	private Date dataCadastro;
	private Date dataPreAcolhimento;
	private int procedencia;
	private String queixa;
	private int atendidaCentro;
	private Long idTecnicoCriacao;
	private Long idTecnicoAlteracao;
	private Date dataCriacao;
	private Date dataAlteracao;
	private Set agendaAtendimentos = new HashSet(0);
	private Set atendimentos = new HashSet(0);
	private Set encaminhamentos = new HashSet(0);

	public PreAcolhimento() {
	}

	public PreAcolhimento(long id, Centro centro, Tecnico tecnico, Usuaria usuaria, Date dataCadastro,
			Date dataPreAcolhimento, int procedencia, int atendidaCentro) {
		this.id = id;
		this.centro = centro;
		this.tecnico = tecnico;
		this.usuaria = usuaria;
		this.dataCadastro = dataCadastro;
		this.dataPreAcolhimento = dataPreAcolhimento;
		this.procedencia = procedencia;
		this.atendidaCentro = atendidaCentro;
	}

	public PreAcolhimento(long id, Centro centro, OrigemEncaminhamento origemEncaminhamento, Tecnico tecnico,
			Usuaria usuaria, Date dataCadastro, Date dataPreAcolhimento, int procedencia, String queixa,
			int atendidaCentro, Long idTecnicoCriacao, Long idTecnicoAlteracao, Date dataCriacao, Date dataAlteracao,
			Set agendaAtendimentos, Set atendimentos, Set encaminhamentos) {
		this.id = id;
		this.centro = centro;
		this.origemEncaminhamento = origemEncaminhamento;
		this.tecnico = tecnico;
		this.usuaria = usuaria;
		this.dataCadastro = dataCadastro;
		this.dataPreAcolhimento = dataPreAcolhimento;
		this.procedencia = procedencia;
		this.queixa = queixa;
		this.atendidaCentro = atendidaCentro;
		this.idTecnicoCriacao = idTecnicoCriacao;
		this.idTecnicoAlteracao = idTecnicoAlteracao;
		this.dataCriacao = dataCriacao;
		this.dataAlteracao = dataAlteracao;
		this.agendaAtendimentos = agendaAtendimentos;
		this.atendimentos = atendimentos;
		this.encaminhamentos = encaminhamentos;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_centro", nullable = false)
	public Centro getCentro() {
		return this.centro;
	}

	public void setCentro(Centro centro) {
		this.centro = centro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_origem_encaminhamento")
	public OrigemEncaminhamento getOrigemEncaminhamento() {
		return this.origemEncaminhamento;
	}

	public void setOrigemEncaminhamento(OrigemEncaminhamento origemEncaminhamento) {
		this.origemEncaminhamento = origemEncaminhamento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tecnico", nullable = false)
	public Tecnico getTecnico() {
		return this.tecnico;
	}

	public void setTecnico(Tecnico tecnico) {
		this.tecnico = tecnico;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuaria", nullable = false)
	public Usuaria getUsuaria() {
		return this.usuaria;
	}

	public void setUsuaria(Usuaria usuaria) {
		this.usuaria = usuaria;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_cadastro", nullable = false, length = 29)
	public Date getDataCadastro() {
		return this.dataCadastro;
	}

	public void setDataCadastro(Date dataCadastro) {
		this.dataCadastro = dataCadastro;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data_pre_acolhimento", nullable = false, length = 13)
	public Date getDataPreAcolhimento() {
		return this.dataPreAcolhimento;
	}

	public void setDataPreAcolhimento(Date dataPreAcolhimento) {
		this.dataPreAcolhimento = dataPreAcolhimento;
	}

	@Column(name = "procedencia", nullable = false)
	public int getProcedencia() {
		return this.procedencia;
	}

	public void setProcedencia(int procedencia) {
		this.procedencia = procedencia;
	}

	@Column(name = "queixa")
	public String getQueixa() {
		return this.queixa;
	}

	public void setQueixa(String queixa) {
		this.queixa = queixa;
	}

	@Column(name = "atendida_centro", nullable = false)
	public int getAtendidaCentro() {
		return this.atendidaCentro;
	}

	public void setAtendidaCentro(int atendidaCentro) {
		this.atendidaCentro = atendidaCentro;
	}

	@Column(name = "id_tecnico_criacao")
	public Long getIdTecnicoCriacao() {
		return this.idTecnicoCriacao;
	}

	public void setIdTecnicoCriacao(Long idTecnicoCriacao) {
		this.idTecnicoCriacao = idTecnicoCriacao;
	}

	@Column(name = "id_tecnico_alteracao")
	public Long getIdTecnicoAlteracao() {
		return this.idTecnicoAlteracao;
	}

	public void setIdTecnicoAlteracao(Long idTecnicoAlteracao) {
		this.idTecnicoAlteracao = idTecnicoAlteracao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_criacao", length = 29)
	public Date getDataCriacao() {
		return this.dataCriacao;
	}

	public void setDataCriacao(Date dataCriacao) {
		this.dataCriacao = dataCriacao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_alteracao", length = 29)
	public Date getDataAlteracao() {
		return this.dataAlteracao;
	}

	public void setDataAlteracao(Date dataAlteracao) {
		this.dataAlteracao = dataAlteracao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "preAcolhimento")
	public Set getAgendaAtendimentos() {
		return this.agendaAtendimentos;
	}

	public void setAgendaAtendimentos(Set agendaAtendimentos) {
		this.agendaAtendimentos = agendaAtendimentos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "preAcolhimento")
	public Set getAtendimentos() {
		return this.atendimentos;
	}

	public void setAtendimentos(Set atendimentos) {
		this.atendimentos = atendimentos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "preAcolhimento")
	public Set getEncaminhamentos() {
		return this.encaminhamentos;
	}

	public void setEncaminhamentos(Set encaminhamentos) {
		this.encaminhamentos = encaminhamentos;
	}

}
