package br.gov.pa.prodepa;
// Generated Nov 1, 2019 4:29:22 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ProgramaGoverno generated by hbm2java
 */
@Entity
@Table(name = "programa_governo", uniqueConstraints = @UniqueConstraint(columnNames = "descricao"))
public class ProgramaGoverno implements java.io.Serializable {

	private long id;
	private String descricao;
	private int situacao;
	private Set residentes = new HashSet(0);
	private Set usuarias = new HashSet(0);

	public ProgramaGoverno() {
	}

	public ProgramaGoverno(long id, String descricao, int situacao) {
		this.id = id;
		this.descricao = descricao;
		this.situacao = situacao;
	}

	public ProgramaGoverno(long id, String descricao, int situacao, Set residentes, Set usuarias) {
		this.id = id;
		this.descricao = descricao;
		this.situacao = situacao;
		this.residentes = residentes;
		this.usuarias = usuarias;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "descricao", unique = true, nullable = false)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "situacao", nullable = false)
	public int getSituacao() {
		return this.situacao;
	}

	public void setSituacao(int situacao) {
		this.situacao = situacao;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "programa_governo_residente", joinColumns = {
			@JoinColumn(name = "id_programa_governo", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "id_residente", nullable = false, updatable = false) })
	public Set getResidentes() {
		return this.residentes;
	}

	public void setResidentes(Set residentes) {
		this.residentes = residentes;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "programa_governo_usuaria", joinColumns = {
			@JoinColumn(name = "id_programa_governo", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "id_usuaria", nullable = false, updatable = false) })
	public Set getUsuarias() {
		return this.usuarias;
	}

	public void setUsuarias(Set usuarias) {
		this.usuarias = usuarias;
	}

}
