package br.gov.pa.prodepa;
// Generated Nov 1, 2019 4:29:22 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Relatorios generated by hbm2java
 */
@Entity
@Table(name = "relatorios")
public class Relatorios implements java.io.Serializable {

	private long id;
	private String nomeRelatorio;
	private String nomeColuna;
	private String comandoSql;
	private int situacao;

	public Relatorios() {
	}

	public Relatorios(long id, String nomeRelatorio, String nomeColuna, String comandoSql, int situacao) {
		this.id = id;
		this.nomeRelatorio = nomeRelatorio;
		this.nomeColuna = nomeColuna;
		this.comandoSql = comandoSql;
		this.situacao = situacao;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "nome_relatorio", nullable = false, length = 500)
	public String getNomeRelatorio() {
		return this.nomeRelatorio;
	}

	public void setNomeRelatorio(String nomeRelatorio) {
		this.nomeRelatorio = nomeRelatorio;
	}

	@Column(name = "nome_coluna", nullable = false)
	public String getNomeColuna() {
		return this.nomeColuna;
	}

	public void setNomeColuna(String nomeColuna) {
		this.nomeColuna = nomeColuna;
	}

	@Column(name = "comando_sql", nullable = false)
	public String getComandoSql() {
		return this.comandoSql;
	}

	public void setComandoSql(String comandoSql) {
		this.comandoSql = comandoSql;
	}

	@Column(name = "situacao", nullable = false)
	public int getSituacao() {
		return this.situacao;
	}

	public void setSituacao(int situacao) {
		this.situacao = situacao;
	}

}
