package br.gov.pa.prodepa;
// Generated Nov 1, 2019 4:29:22 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Religiao generated by hbm2java
 */
@Entity
@Table(name = "religiao", uniqueConstraints = @UniqueConstraint(columnNames = "descricao"))
public class Religiao implements java.io.Serializable {

	private long id;
	private String descricao;
	private Integer situacao;
	private Set agressors = new HashSet(0);
	private Set usuarias = new HashSet(0);

	public Religiao() {
	}

	public Religiao(long id, String descricao) {
		this.id = id;
		this.descricao = descricao;
	}

	public Religiao(long id, String descricao, Integer situacao, Set agressors, Set usuarias) {
		this.id = id;
		this.descricao = descricao;
		this.situacao = situacao;
		this.agressors = agressors;
		this.usuarias = usuarias;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "descricao", unique = true, nullable = false)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "situacao")
	public Integer getSituacao() {
		return this.situacao;
	}

	public void setSituacao(Integer situacao) {
		this.situacao = situacao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "religiao")
	public Set getAgressors() {
		return this.agressors;
	}

	public void setAgressors(Set agressors) {
		this.agressors = agressors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "religiao")
	public Set getUsuarias() {
		return this.usuarias;
	}

	public void setUsuarias(Set usuarias) {
		this.usuarias = usuarias;
	}

}
