package br.gov.pa.prodepa;
// Generated Nov 1, 2019 4:29:22 PM by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Residente generated by hbm2java
 */
@Entity
@Table(name = "residente")
public class Residente implements java.io.Serializable {

	private long id;
	private GrauRelacao grauRelacao;
	private Ocupacao ocupacao;
	private Usuaria usuaria;
	private String nome;
	private Integer possuiRenda;
	private BigDecimal renda;
	private Integer trabalha;
	private String motivoNaoTrabalha;
	private int situacao;
	private String observacao;
	private Set programaGovernos = new HashSet(0);

	public Residente() {
	}

	public Residente(long id, GrauRelacao grauRelacao, Usuaria usuaria, String nome, int situacao) {
		this.id = id;
		this.grauRelacao = grauRelacao;
		this.usuaria = usuaria;
		this.nome = nome;
		this.situacao = situacao;
	}

	public Residente(long id, GrauRelacao grauRelacao, Ocupacao ocupacao, Usuaria usuaria, String nome,
			Integer possuiRenda, BigDecimal renda, Integer trabalha, String motivoNaoTrabalha, int situacao,
			String observacao, Set programaGovernos) {
		this.id = id;
		this.grauRelacao = grauRelacao;
		this.ocupacao = ocupacao;
		this.usuaria = usuaria;
		this.nome = nome;
		this.possuiRenda = possuiRenda;
		this.renda = renda;
		this.trabalha = trabalha;
		this.motivoNaoTrabalha = motivoNaoTrabalha;
		this.situacao = situacao;
		this.observacao = observacao;
		this.programaGovernos = programaGovernos;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_grau_relacao", nullable = false)
	public GrauRelacao getGrauRelacao() {
		return this.grauRelacao;
	}

	public void setGrauRelacao(GrauRelacao grauRelacao) {
		this.grauRelacao = grauRelacao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_ocupacao")
	public Ocupacao getOcupacao() {
		return this.ocupacao;
	}

	public void setOcupacao(Ocupacao ocupacao) {
		this.ocupacao = ocupacao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuaria", nullable = false)
	public Usuaria getUsuaria() {
		return this.usuaria;
	}

	public void setUsuaria(Usuaria usuaria) {
		this.usuaria = usuaria;
	}

	@Column(name = "nome", nullable = false)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "possui_renda")
	public Integer getPossuiRenda() {
		return this.possuiRenda;
	}

	public void setPossuiRenda(Integer possuiRenda) {
		this.possuiRenda = possuiRenda;
	}

	@Column(name = "renda", precision = 9)
	public BigDecimal getRenda() {
		return this.renda;
	}

	public void setRenda(BigDecimal renda) {
		this.renda = renda;
	}

	@Column(name = "trabalha")
	public Integer getTrabalha() {
		return this.trabalha;
	}

	public void setTrabalha(Integer trabalha) {
		this.trabalha = trabalha;
	}

	@Column(name = "motivo_nao_trabalha")
	public String getMotivoNaoTrabalha() {
		return this.motivoNaoTrabalha;
	}

	public void setMotivoNaoTrabalha(String motivoNaoTrabalha) {
		this.motivoNaoTrabalha = motivoNaoTrabalha;
	}

	@Column(name = "situacao", nullable = false)
	public int getSituacao() {
		return this.situacao;
	}

	public void setSituacao(int situacao) {
		this.situacao = situacao;
	}

	@Column(name = "observacao")
	public String getObservacao() {
		return this.observacao;
	}

	public void setObservacao(String observacao) {
		this.observacao = observacao;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "programa_governo_residente", joinColumns = {
			@JoinColumn(name = "id_residente", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "id_programa_governo", nullable = false, updatable = false) })
	public Set getProgramaGovernos() {
		return this.programaGovernos;
	}

	public void setProgramaGovernos(Set programaGovernos) {
		this.programaGovernos = programaGovernos;
	}

}
