package br.gov.pa.prodepa;
// Generated Nov 1, 2019 4:29:22 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TecnicoCentro generated by hbm2java
 */
@Entity
@Table(name = "tecnico_centro", uniqueConstraints = @UniqueConstraint(columnNames = { "id", "situacao" }))
public class TecnicoCentro implements java.io.Serializable {

	private long id;
	private Centro centro;
	private Tecnico tecnico;
	private Date dataInicio;
	private Date dataFim;
	private int situacao;

	public TecnicoCentro() {
	}

	public TecnicoCentro(long id, Centro centro, Tecnico tecnico, Date dataInicio, int situacao) {
		this.id = id;
		this.centro = centro;
		this.tecnico = tecnico;
		this.dataInicio = dataInicio;
		this.situacao = situacao;
	}

	public TecnicoCentro(long id, Centro centro, Tecnico tecnico, Date dataInicio, Date dataFim, int situacao) {
		this.id = id;
		this.centro = centro;
		this.tecnico = tecnico;
		this.dataInicio = dataInicio;
		this.dataFim = dataFim;
		this.situacao = situacao;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_centro", nullable = false)
	public Centro getCentro() {
		return this.centro;
	}

	public void setCentro(Centro centro) {
		this.centro = centro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tecnico", nullable = false)
	public Tecnico getTecnico() {
		return this.tecnico;
	}

	public void setTecnico(Tecnico tecnico) {
		this.tecnico = tecnico;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data_inicio", nullable = false, length = 13)
	public Date getDataInicio() {
		return this.dataInicio;
	}

	public void setDataInicio(Date dataInicio) {
		this.dataInicio = dataInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data_fim", length = 13)
	public Date getDataFim() {
		return this.dataFim;
	}

	public void setDataFim(Date dataFim) {
		this.dataFim = dataFim;
	}

	@Column(name = "situacao", nullable = false)
	public int getSituacao() {
		return this.situacao;
	}

	public void setSituacao(int situacao) {
		this.situacao = situacao;
	}

}
