package br.gov.pa.prodepa;
// Generated Nov 1, 2019 4:29:22 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoMedicacao generated by hbm2java
 */
@Entity
@Table(name = "tipo_medicacao")
public class TipoMedicacao implements java.io.Serializable {

	private long id;
	private String descricao;
	private int situacao;
	private Set agressorTipoMedicacaos = new HashSet(0);
	private Set usuariaTipoMedicacaos = new HashSet(0);

	public TipoMedicacao() {
	}

	public TipoMedicacao(long id, String descricao, int situacao) {
		this.id = id;
		this.descricao = descricao;
		this.situacao = situacao;
	}

	public TipoMedicacao(long id, String descricao, int situacao, Set agressorTipoMedicacaos,
			Set usuariaTipoMedicacaos) {
		this.id = id;
		this.descricao = descricao;
		this.situacao = situacao;
		this.agressorTipoMedicacaos = agressorTipoMedicacaos;
		this.usuariaTipoMedicacaos = usuariaTipoMedicacaos;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "descricao", nullable = false)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "situacao", nullable = false)
	public int getSituacao() {
		return this.situacao;
	}

	public void setSituacao(int situacao) {
		this.situacao = situacao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoMedicacao")
	public Set getAgressorTipoMedicacaos() {
		return this.agressorTipoMedicacaos;
	}

	public void setAgressorTipoMedicacaos(Set agressorTipoMedicacaos) {
		this.agressorTipoMedicacaos = agressorTipoMedicacaos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoMedicacao")
	public Set getUsuariaTipoMedicacaos() {
		return this.usuariaTipoMedicacaos;
	}

	public void setUsuariaTipoMedicacaos(Set usuariaTipoMedicacaos) {
		this.usuariaTipoMedicacaos = usuariaTipoMedicacaos;
	}

}
