package br.gov.pa.prodepa;
// Generated Nov 1, 2019 4:29:22 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TipoProblemaPsicologico generated by hbm2java
 */
@Entity
@Table(name = "tipo_problema_psicologico", uniqueConstraints = @UniqueConstraint(columnNames = "descricao"))
public class TipoProblemaPsicologico implements java.io.Serializable {

	private long id;
	private String descricao;
	private int situacao;
	private Set usuarias = new HashSet(0);
	private Set dependentes = new HashSet(0);

	public TipoProblemaPsicologico() {
	}

	public TipoProblemaPsicologico(long id, String descricao, int situacao) {
		this.id = id;
		this.descricao = descricao;
		this.situacao = situacao;
	}

	public TipoProblemaPsicologico(long id, String descricao, int situacao, Set usuarias, Set dependentes) {
		this.id = id;
		this.descricao = descricao;
		this.situacao = situacao;
		this.usuarias = usuarias;
		this.dependentes = dependentes;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "descricao", unique = true, nullable = false)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "situacao", nullable = false)
	public int getSituacao() {
		return this.situacao;
	}

	public void setSituacao(int situacao) {
		this.situacao = situacao;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "problema_psicologico_usuaria", joinColumns = {
			@JoinColumn(name = "id_tipo_problema_psicologico", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "id_usuaria", nullable = false, updatable = false) })
	public Set getUsuarias() {
		return this.usuarias;
	}

	public void setUsuarias(Set usuarias) {
		this.usuarias = usuarias;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "problema_psicologico_dependente", joinColumns = {
			@JoinColumn(name = "id_tipo_problema_psicologico", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "id_dependente", nullable = false, updatable = false) })
	public Set getDependentes() {
		return this.dependentes;
	}

	public void setDependentes(Set dependentes) {
		this.dependentes = dependentes;
	}

}
