package br.gov.pa.prodepa;
// Generated Nov 1, 2019 4:29:22 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UsuariaTipoEntorpecente generated by hbm2java
 */
@Entity
@Table(name = "usuaria_tipo_entorpecente")
public class UsuariaTipoEntorpecente implements java.io.Serializable {

	private UsuariaTipoEntorpecenteId id;
	private TipoEntorpecente tipoEntorpecente;
	private Usuaria usuaria;
	private Integer frequenciaUso;
	private Integer fazUso;

	public UsuariaTipoEntorpecente() {
	}

	public UsuariaTipoEntorpecente(UsuariaTipoEntorpecenteId id, TipoEntorpecente tipoEntorpecente, Usuaria usuaria) {
		this.id = id;
		this.tipoEntorpecente = tipoEntorpecente;
		this.usuaria = usuaria;
	}

	public UsuariaTipoEntorpecente(UsuariaTipoEntorpecenteId id, TipoEntorpecente tipoEntorpecente, Usuaria usuaria,
			Integer frequenciaUso, Integer fazUso) {
		this.id = id;
		this.tipoEntorpecente = tipoEntorpecente;
		this.usuaria = usuaria;
		this.frequenciaUso = frequenciaUso;
		this.fazUso = fazUso;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idTipoEntorpecente", column = @Column(name = "id_tipo_entorpecente", nullable = false)),
			@AttributeOverride(name = "idUsuaria", column = @Column(name = "id_usuaria", nullable = false)) })
	public UsuariaTipoEntorpecenteId getId() {
		return this.id;
	}

	public void setId(UsuariaTipoEntorpecenteId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_entorpecente", nullable = false, insertable = false, updatable = false)
	public TipoEntorpecente getTipoEntorpecente() {
		return this.tipoEntorpecente;
	}

	public void setTipoEntorpecente(TipoEntorpecente tipoEntorpecente) {
		this.tipoEntorpecente = tipoEntorpecente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuaria", nullable = false, insertable = false, updatable = false)
	public Usuaria getUsuaria() {
		return this.usuaria;
	}

	public void setUsuaria(Usuaria usuaria) {
		this.usuaria = usuaria;
	}

	@Column(name = "frequencia_uso")
	public Integer getFrequenciaUso() {
		return this.frequenciaUso;
	}

	public void setFrequenciaUso(Integer frequenciaUso) {
		this.frequenciaUso = frequenciaUso;
	}

	@Column(name = "faz_uso")
	public Integer getFazUso() {
		return this.fazUso;
	}

	public void setFazUso(Integer fazUso) {
		this.fazUso = fazUso;
	}

}
