package br.gov.pa.prodepa;
// Generated Nov 1, 2019 4:29:22 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UsuariaViolencia generated by hbm2java
 */
@Entity
@Table(name = "usuaria_violencia")
public class UsuariaViolencia implements java.io.Serializable {

	private long id;
	private GrauRelacao grauRelacao;
	private Usuaria usuaria;
	private Violencia violencia;
	private String fase;

	public UsuariaViolencia() {
	}

	public UsuariaViolencia(long id, Usuaria usuaria, Violencia violencia) {
		this.id = id;
		this.usuaria = usuaria;
		this.violencia = violencia;
	}

	public UsuariaViolencia(long id, GrauRelacao grauRelacao, Usuaria usuaria, Violencia violencia, String fase) {
		this.id = id;
		this.grauRelacao = grauRelacao;
		this.usuaria = usuaria;
		this.violencia = violencia;
		this.fase = fase;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_grau_relacao")
	public GrauRelacao getGrauRelacao() {
		return this.grauRelacao;
	}

	public void setGrauRelacao(GrauRelacao grauRelacao) {
		this.grauRelacao = grauRelacao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuaria", nullable = false)
	public Usuaria getUsuaria() {
		return this.usuaria;
	}

	public void setUsuaria(Usuaria usuaria) {
		this.usuaria = usuaria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_violencia", nullable = false)
	public Violencia getViolencia() {
		return this.violencia;
	}

	public void setViolencia(Violencia violencia) {
		this.violencia = violencia;
	}

	@Column(name = "fase")
	public String getFase() {
		return this.fase;
	}

	public void setFase(String fase) {
		this.fase = fase;
	}

}
