package br.gov.pa.prodepa;
// Generated Nov 1, 2019 4:29:22 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UsuariaTipoMedicacao generated by hbm2java
 */
@Entity
@Table(name = "usuaria_tipo_medicacao")
public class UsuariaTipoMedicacao implements java.io.Serializable {

	private UsuariaTipoMedicacaoId id;
	private TipoMedicacao tipoMedicacao;
	private Usuaria usuaria;
	private int frequenciaUso;

	public UsuariaTipoMedicacao() {
	}

	public UsuariaTipoMedicacao(UsuariaTipoMedicacaoId id, TipoMedicacao tipoMedicacao, Usuaria usuaria,
			int frequenciaUso) {
		this.id = id;
		this.tipoMedicacao = tipoMedicacao;
		this.usuaria = usuaria;
		this.frequenciaUso = frequenciaUso;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idTipoMedicacao", column = @Column(name = "id_tipo_medicacao", nullable = false)),
			@AttributeOverride(name = "idUsuaria", column = @Column(name = "id_usuaria", nullable = false)) })
	public UsuariaTipoMedicacaoId getId() {
		return this.id;
	}

	public void setId(UsuariaTipoMedicacaoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_medicacao", nullable = false, insertable = false, updatable = false)
	public TipoMedicacao getTipoMedicacao() {
		return this.tipoMedicacao;
	}

	public void setTipoMedicacao(TipoMedicacao tipoMedicacao) {
		this.tipoMedicacao = tipoMedicacao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuaria", nullable = false, insertable = false, updatable = false)
	public Usuaria getUsuaria() {
		return this.usuaria;
	}

	public void setUsuaria(Usuaria usuaria) {
		this.usuaria = usuaria;
	}

	@Column(name = "frequencia_uso", nullable = false)
	public int getFrequenciaUso() {
		return this.frequenciaUso;
	}

	public void setFrequenciaUso(int frequenciaUso) {
		this.frequenciaUso = frequenciaUso;
	}

}
