package br.gov.pa.prodepa;
// Generated Nov 1, 2019 4:29:22 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsuariaTipoMedicacaoId generated by hbm2java
 */
@Embeddable
public class UsuariaTipoMedicacaoId implements java.io.Serializable {

	private long idTipoMedicacao;
	private long idUsuaria;

	public UsuariaTipoMedicacaoId() {
	}

	public UsuariaTipoMedicacaoId(long idTipoMedicacao, long idUsuaria) {
		this.idTipoMedicacao = idTipoMedicacao;
		this.idUsuaria = idUsuaria;
	}

	@Column(name = "id_tipo_medicacao", nullable = false)
	public long getIdTipoMedicacao() {
		return this.idTipoMedicacao;
	}

	public void setIdTipoMedicacao(long idTipoMedicacao) {
		this.idTipoMedicacao = idTipoMedicacao;
	}

	@Column(name = "id_usuaria", nullable = false)
	public long getIdUsuaria() {
		return this.idUsuaria;
	}

	public void setIdUsuaria(long idUsuaria) {
		this.idUsuaria = idUsuaria;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsuariaTipoMedicacaoId))
			return false;
		UsuariaTipoMedicacaoId castOther = (UsuariaTipoMedicacaoId) other;

		return (this.getIdTipoMedicacao() == castOther.getIdTipoMedicacao())
				&& (this.getIdUsuaria() == castOther.getIdUsuaria());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdTipoMedicacao();
		result = 37 * result + (int) this.getIdUsuaria();
		return result;
	}

}
