package br.gov.pa.prodepa;
// Generated Nov 1, 2019 4:29:22 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Violencia generated by hbm2java
 */
@Entity
@Table(name = "violencia", uniqueConstraints = @UniqueConstraint(columnNames = "descricao"))
public class Violencia implements java.io.Serializable {

	private long id;
	private String descricao;
	private int situacao;
	private Set atendimentos = new HashSet(0);
	private Set detalheViolencias = new HashSet(0);
	private Set usuariaViolencias = new HashSet(0);

	public Violencia() {
	}

	public Violencia(long id, String descricao, int situacao) {
		this.id = id;
		this.descricao = descricao;
		this.situacao = situacao;
	}

	public Violencia(long id, String descricao, int situacao, Set atendimentos, Set detalheViolencias,
			Set usuariaViolencias) {
		this.id = id;
		this.descricao = descricao;
		this.situacao = situacao;
		this.atendimentos = atendimentos;
		this.detalheViolencias = detalheViolencias;
		this.usuariaViolencias = usuariaViolencias;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "descricao", unique = true, nullable = false)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "situacao", nullable = false)
	public int getSituacao() {
		return this.situacao;
	}

	public void setSituacao(int situacao) {
		this.situacao = situacao;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "atendimento_violencia", joinColumns = {
			@JoinColumn(name = "id_violencia", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "id_atendimento", nullable = false, updatable = false) })
	public Set getAtendimentos() {
		return this.atendimentos;
	}

	public void setAtendimentos(Set atendimentos) {
		this.atendimentos = atendimentos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "violencia")
	public Set getDetalheViolencias() {
		return this.detalheViolencias;
	}

	public void setDetalheViolencias(Set detalheViolencias) {
		this.detalheViolencias = detalheViolencias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "violencia")
	public Set getUsuariaViolencias() {
		return this.usuariaViolencias;
	}

	public void setUsuariaViolencias(Set usuariaViolencias) {
		this.usuariaViolencias = usuariaViolencias;
	}

}
