package br.gov.pa.prodepa;
// Generated Nov 1, 2019 4:29:22 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VwMunicipio generated by hbm2java
 */
@Entity
@Table(name = "vw_municipio")
public class VwMunicipio implements java.io.Serializable {

	private VwMunicipioId id;

	public VwMunicipio() {
	}

	public VwMunicipio(VwMunicipioId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idMunicipio", column = @Column(name = "id_municipio")),
			@AttributeOverride(name = "nomeMunicipio", column = @Column(name = "nome_municipio", length = 100)),
			@AttributeOverride(name = "idUf", column = @Column(name = "id_uf")),
			@AttributeOverride(name = "nomeUf", column = @Column(name = "nome_uf", length = 100)),
			@AttributeOverride(name = "siglaUf", column = @Column(name = "sigla_uf", length = 2)) })
	public VwMunicipioId getId() {
		return this.id;
	}

	public void setId(VwMunicipioId id) {
		this.id = id;
	}

}
