package br.gov.pa.prodepa;
// Generated Nov 1, 2019 4:29:22 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VwUsuarioAplicacao generated by hbm2java
 */
@Entity
@Table(name = "vw_usuario_aplicacao")
public class VwUsuarioAplicacao implements java.io.Serializable {

	private VwUsuarioAplicacaoId id;

	public VwUsuarioAplicacao() {
	}

	public VwUsuarioAplicacao(VwUsuarioAplicacaoId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idUsuario", column = @Column(name = "id_usuario")),
			@AttributeOverride(name = "idAplicacao", column = @Column(name = "id_aplicacao")),
			@AttributeOverride(name = "nomeUsuario", column = @Column(name = "nome_usuario")),
			@AttributeOverride(name = "cpf", column = @Column(name = "cpf", length = 11)) })
	public VwUsuarioAplicacaoId getId() {
		return this.id;
	}

	public void setId(VwUsuarioAplicacaoId id) {
		this.id = id;
	}

}
