package br.gov.pa.prodepa;
// Generated Nov 1, 2019 4:29:22 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VwUsuarioAplicacaoId generated by hbm2java
 */
@Embeddable
public class VwUsuarioAplicacaoId implements java.io.Serializable {

	private Long idUsuario;
	private Long idAplicacao;
	private String nomeUsuario;
	private String cpf;

	public VwUsuarioAplicacaoId() {
	}

	public VwUsuarioAplicacaoId(Long idUsuario, Long idAplicacao, String nomeUsuario, String cpf) {
		this.idUsuario = idUsuario;
		this.idAplicacao = idAplicacao;
		this.nomeUsuario = nomeUsuario;
		this.cpf = cpf;
	}

	@Column(name = "id_usuario")
	public Long getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Long idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "id_aplicacao")
	public Long getIdAplicacao() {
		return this.idAplicacao;
	}

	public void setIdAplicacao(Long idAplicacao) {
		this.idAplicacao = idAplicacao;
	}

	@Column(name = "nome_usuario")
	public String getNomeUsuario() {
		return this.nomeUsuario;
	}

	public void setNomeUsuario(String nomeUsuario) {
		this.nomeUsuario = nomeUsuario;
	}

	@Column(name = "cpf", length = 11)
	public String getCpf() {
		return this.cpf;
	}

	public void setCpf(String cpf) {
		this.cpf = cpf;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VwUsuarioAplicacaoId))
			return false;
		VwUsuarioAplicacaoId castOther = (VwUsuarioAplicacaoId) other;

		return ((this.getIdUsuario() == castOther.getIdUsuario()) || (this.getIdUsuario() != null
				&& castOther.getIdUsuario() != null && this.getIdUsuario().equals(castOther.getIdUsuario())))
				&& ((this.getIdAplicacao() == castOther.getIdAplicacao())
						|| (this.getIdAplicacao() != null && castOther.getIdAplicacao() != null
								&& this.getIdAplicacao().equals(castOther.getIdAplicacao())))
				&& ((this.getNomeUsuario() == castOther.getNomeUsuario())
						|| (this.getNomeUsuario() != null && castOther.getNomeUsuario() != null
								&& this.getNomeUsuario().equals(castOther.getNomeUsuario())))
				&& ((this.getCpf() == castOther.getCpf()) || (this.getCpf() != null && castOther.getCpf() != null
						&& this.getCpf().equals(castOther.getCpf())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdUsuario() == null ? 0 : this.getIdUsuario().hashCode());
		result = 37 * result + (getIdAplicacao() == null ? 0 : this.getIdAplicacao().hashCode());
		result = 37 * result + (getNomeUsuario() == null ? 0 : this.getNomeUsuario().hashCode());
		result = 37 * result + (getCpf() == null ? 0 : this.getCpf().hashCode());
		return result;
	}

}
